SELECT :PROYEAR, INFO.DEPARTMENTNM, INFO.DEPT_BANGLA, INFO.SECTIONNM, INFO.SEC_BANGLA, 
INFO.LINENO, INFO.CARDNO, INFO.EMPNAME, INFO.DESIGNATION, INFO.DESIGNATION_BANGLA, 
INFO.JOINING_DATE, DES.SALGRADE, INFO.GROSSSALARY, ROUND(((INFO.GROSSSALARY*5)/100)) AS FIVE_PER_INCR, 
(INFO.GROSSSALARY+ROUND(((INFO.GROSSSALARY*5)/100))) AS UPDATE_GROSS, :EFFECTIVE_DATE,
INFO.WORKERTYPE, INFO.COMPANY
FROM TB_PERSONAL_INFO INFO, TB_DESIGNATION_INFO DES
WHERE DES.DESIGNATION=INFO.DESIGNATION


INSERT INTO TB_PROMOTION_INFO PRO_INFO
(SLNO,PROYEAR, CARDNO, EMPNAME, JOININGDATE, CURRDESIGNATION, PRODESIGNATION, CURRSALARY, 
PROSALARY, SALARYGRD, EFFECTIVEDATE, WORKERTYPE, COMPANY, REMARKS, FINMONTH, PROCESSBY, PROCESSDATE, 
PRO_SAL_GRD, PRO_WORKER_TYPE, DESIGNATION_BANGLA, PRO_DESIG_BANGLA, DEPARTMENTNM, DEPT_BANGLA, SECTIONNM, 
SECT_BANGLA, LINENO) 
(SELECT 2020, INFO.CARDNO,INFO.EMPNAME,INFO.JOINING_DATE,INFO.DESIGNATION,INFO.DESIGNATION,INFO.GROSSSALARY,
(INFO.GROSSSALARY+ROUND(((INFO.GROSSSALARY*5)/100))),DES.SALGRADE,:EFFECTIVE_DATE,INFO.WORKERTYPE,INFO.COMPANY,
'YrS Increment','December','factory1','15-DEC-2020',DES.SALGRADE,INFO.WORKERTYPE,INFO.DESIGNATION_BANGLA,
INFO.DESIGNATION_BANGLA,INFO.DEPARTMENTNM,INFO.DEPT_BANGLA,INFO.SECTIONNM, INFO.SEC_BANGLA, 
INFO.LINENO 
FROM TB_PERSONAL_INFO INFO, TB_DESIGNATION_INFO DES
WHERE DES.DESIGNATION=INFO.DESIGNATION
AND	  INFO.ACTIVE=0)




