--- FOR SEE HOW MANY DAYS ABSENT SELECTED EMP 
SELECT INFO.DEPARTMENTNM, INFO.SECTIONNM, INFO.CARDNO, INFO.EMPNAME, INFO.DESIGNATION, COUNT(ABDAY.PDATE) ABSENT_DAY
FROM TB_PERSONAL_INFO INFO, TB_EMP_ABSENT_DAYS ABDAY
WHERE INFO.COMPANY= 'Apparel Plus Limited.'
AND	  ABDAY.COMPANY=INFO.COMPANY
AND	  INFO.ACTIVE=0
AND	  INFO.CARDNO=ABDAY.CARDNO
GROUP BY INFO.DEPARTMENTNM, INFO.SECTIONNM, INFO.CARDNO, INFO.EMPNAME, INFO.DESIGNATION
ORDER BY CARDNO ASC