INSERT INTO TB_PERSONAL_INFO (
EMPID,DEPARTMENTNM,  SECTIONNM,  LINENO,
CARDNO,  SECRETENO,  EMPNAME,  FATHER_NAME,  MOTHER_NAME,  PRESENT_ADDRESS,
JOINING_DATE,  DESIGNATION,  SALARY_GRADE,  GROSSSALARY,  RESIGNATION_DATE,
BIRTH_DATE,  TSALARY,  GENDER,  BLOODGROUP,  SHIFT,  WORKERTYPE,
HOUSBANDNAME,  PERMANENTADDRESS,  COMPANY,  ACTIVE,  PF,  INRAMT,
WDAY,  PROCESS_DATE,  PROCESS_BY,  OTORG,  OTCOM,  CASH_TYPE,
AC_NO,  SURNAME,  RELIGION,  MOBILE,  OTHERS,  ENMNAME_BANGLA,  DESIGNATION_BANGLA,
DEPT_BANGLA,  SEC_BANGLA,  MARITAL_STATUS,  BANK_NAME,  PAY_SAL,  PAY_OTHER,  PRESENT_PO,
PRESENT_PS,  PRESENT_DIST,  PRESENT_VIL_BAN,  PRESENT_PO_BAN,  PRESENT_PS_BAN,  
PRESENT_DIST_BAN,  PERMANENT_PO,  PERMANENT_PS,  PERMANENT_DIST,  PERMANENT_VIL_BAN,
PERMANENT_PO_BAN,  PERMANENT_PS_BAN,  PERMANENT_DIST_BAN,  FATHER_NAME_BAN,  MOTHER_NAME_BAN,
SPOUSE_NAME_BAN,  TEAM_NAME ,  TEAM_DESIGNATION ,  TEAM_BOX_NO,  TEAM_JOIN_DATE)
SELECT (11115+empid), DEPARTMENTNM,  SECTIONNM,  LINENO,
CARDNO,  SECRETENO,  EMPNAME,  FATHER_NAME,  MOTHER_NAME,  PRESENT_ADDRESS,
JOINING_DATE,  DESIGNATION,  SALARY_GRADE,  GROSSSALARY,  RESIGNATION_DATE,
BIRTH_DATE,  TSALARY,  GENDER,  BLOODGROUP,  SHIFT,  WORKERTYPE,
HOUSBANDNAME,  PERMANENTADDRESS,  'Apparel Plus Ltd.',  ACTIVE,  PF,  INRAMT,
WDAY,  PROCESS_DATE,  PROCESS_BY,  OTORG,  OTCOM,  CASH_TYPE,
AC_NO,  SURNAME,  RELIGION,  MOBILE,  OTHERS,  ENMNAME_BANGLA,  DESIGNATION_BANGLA,
DEPT_BANGLA,  SEC_BANGLA,  MARITAL_STATUS,  BANK_NAME,  PAY_SAL,  PAY_OTHER,  PRESENT_PO,
PRESENT_PS,  PRESENT_DIST,  PRESENT_VIL_BAN,  PRESENT_PO_BAN,  PRESENT_PS_BAN,  
PRESENT_DIST_BAN,  PERMANENT_PO,  PERMANENT_PS,  PERMANENT_DIST,  PERMANENT_VIL_BAN,
PERMANENT_PO_BAN,  PERMANENT_PS_BAN,  PERMANENT_DIST_BAN,  FATHER_NAME_BAN,  MOTHER_NAME_BAN,
SPOUSE_NAME_BAN,  TEAM_NAME ,  TEAM_DESIGNATION ,  TEAM_BOX_NO,  TEAM_JOIN_DATE
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  RESIGNATION_DATE >= '01-June-2020'



select company, cardno, count(cardno) from TB_PERSONAL_INFO_SIGN
--where empid>11115
group by company,cardno 


select distinct cardno, count(cardno)
FROM TB_PERSONAL_INFO_PICTURE
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=0
AND	  COMPANY !='Apparel Plus Ltd.'
--AND	  RESIGNATION_DATE >= '01-June-2020'
)
group by cardno




select * from tb_personal_info where 
empid>11115





INSERT INTO  TB_PERSONAL_EDUCATIONAL
(EMPID, CARDNO, HIGHEST_DEGREE, LEVEL_DEGREE, INSTITUTE_NAME, PASSING_YR, CLASS_GRADE, SUBJECT, COMPANY)
SELECT (11115+EMPID), CARDNO, HIGHEST_DEGREE, LEVEL_DEGREE, INSTITUTE_NAME, 
PASSING_YR, CLASS_GRADE, SUBJECT,'Apparel Plus Ltd.'
FROM TB_PERSONAL_EDUCATIONAL
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
AND	  RESIGNATION_DATE >= '01-June-2020'
)


INSERT INTO  TB_PERSONAL_EMPLOYMENT
(EMPID, CARDNO,  COMPANY)

(SELECT (11115+EMPID), CARDNO, 'Apparel Plus Ltd.'
FROM TB_PERSONAL_EMPLOYMENT
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=0
AND	  COMPANY ='Apparel Plus Ltd.'
--AND	  RESIGNATION_DATE >= '01-June-2020'
))


INSERT INTO  TB_PERSONAL_INFO_OTHER
(EMPID, CARDNO, SECRETENO, BOOK_SL_NO, OPEN_DATE, EDUCATION, 
PURPOSEOFWORK, PERHRPRODUCTION, PERFORMANCE, COMPANY, NID, SECTIONNM, REF1, 
REF2, TOTALCHILD, MALECHILD, FEMALECHILD, NOMINEENAME, NOMINEEADDRESS, NOMINEERELATION, 
NOMINEEPICTURE, NOMINEE_CELLNO, HEIGHT, WEIGHT, SPECIAL_MARK, OWN_CELLNO, TIN, EMAIL_ADDRESS, 
PASSPORT_NO, BIRTH_CERTIFICATE_NO, DRIVING_LICENCE, EMG_CONTACT_PERSON, 
EMG_CON_PER_RELATION, EMG_CON_PER_CELLNO, EMG_CON_PER_ADDRESS)
(SELECT (11115+EMPID), CARDNO, SECRETENO, BOOK_SL_NO, OPEN_DATE, EDUCATION, 
PURPOSEOFWORK, PERHRPRODUCTION, PERFORMANCE, 'Apparel Plus Ltd.', NID, SECTIONNM, REF1, 
REF2, TOTALCHILD, MALECHILD, FEMALECHILD, NOMINEENAME, NOMINEEADDRESS, NOMINEERELATION, 
NOMINEEPICTURE, NOMINEE_CELLNO, HEIGHT, WEIGHT, SPECIAL_MARK, OWN_CELLNO, TIN, EMAIL_ADDRESS, 
PASSPORT_NO, BIRTH_CERTIFICATE_NO, DRIVING_LICENCE, EMG_CONTACT_PERSON, 
EMG_CON_PER_RELATION, EMG_CON_PER_CELLNO, EMG_CON_PER_ADDRESS
FROM TB_PERSONAL_INFO_OTHER
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
AND	  RESIGNATION_DATE >= '01-June-2020'
))



INSERT INTO  TB_PERSONAL_INFO_PICTURE
(EMPID, DEPARTMENTNM, SECTIONNM, CARDNO, SECRETENO, COMPANY, EMPPICTURE)
(select (11115+empid), DEPARTMENTNM, SECTIONNM,CARDNO, SECRETENO, 'Apparel Plus Ltd.', EMPPICTURE
FROM TB_PERSONAL_INFO_PICTURE
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
--AND	  CARDNO != '19252'
AND	  RESIGNATION_DATE >= '01-June-2020'
))



INSERT INTO TB_PERSONAL_INFO_SIGN
(EMPID, DEPARTMENTNM, SECTIONNM, CARDNO, SECRETENO, COMPANY, EMPSIGN)
(select (11115+empid), DEPARTMENTNM, SECTIONNM, CARDNO, SECRETENO, 'Apparel Plus Ltd.', EMPSIGN
FROM TB_PERSONAL_INFO_SIGN
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
--AND	  CARDNO != '19252'
AND	  RESIGNATION_DATE >= '01-June-2020'
))







INSERT INTO TB_PERSONAL_PROFESSIONAL
(EMPID, CARDNO, CERTIFICATION, INSTITULE, CITY, COUNTRY, START_DATE, END_DATE, COMPANY)
(select (11115+empid), CARDNO, CERTIFICATION, INSTITULE, CITY, COUNTRY, START_DATE, END_DATE, 'Apparel Plus Ltd.'
FROM TB_PERSONAL_PROFESSIONAL
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
--AND	  CARDNO != '19252'
AND	  RESIGNATION_DATE >= '01-June-2020'
))



INSERT INTO TB_PERSONAL_TRAINING
(EMPID, CARDNO, TRAINING_TITLE, TR_DURATION, TR_YEAR, INSTITULE, CITY, COUNTRY, COMPANY)
(select (11115+empid), CARDNO, TRAINING_TITLE, TR_DURATION, TR_YEAR, INSTITULE, CITY, COUNTRY, 'Apparel Plus Ltd.'
FROM TB_PERSONAL_TRAINING
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
--AND	  CARDNO != '19252'
AND	  RESIGNATION_DATE >= '01-June-2020'
))


INSERT INTO TB_PERSONAL_TRAINING
(EMPID, CARDNO, TRAINING_TITLE, TR_DURATION, TR_YEAR, INSTITULE, CITY, COUNTRY, COMPANY)
(select (11115+empid), CARDNO, TRAINING_TITLE, TR_DURATION, TR_YEAR, INSTITULE, CITY, COUNTRY, 'Apparel Plus Ltd.'
FROM TB_PERSONAL_TRAINING
WHERE CARDNO IN (
SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
--AND	  CARDNO != '19252'
AND	  RESIGNATION_DATE >= '01-June-2020'
))





SELECT CARDNO
FROM TB_PERSONAL_INFO 
WHERE ACTIVE=1
AND	  COMPANY !='Apparel Plus Ltd.'
AND	  RESIGNATION_DATE >= '01-June-2020'








--------------- update data master 


insert into tb_data_master
(CARDNO, SECRETENO, PDATE, INTIME, OUTTIME, OTSTART, 
DURATION, LATEHR, EARLYHR, OTMIN, OTPART, LATESTATUS, 
EARLYSTATUS, COMPANY, YES_NOT, ISLN, SECTIONNM, SHIFT, 
LINENO, FINYEAR, FINMONTH, LATEDED, EARLYDED, OTHR, 
OTHRPART, PSATUS, STATUSDAY, TF, OUTTIME_V, EARLYHR_V, 
EARLYSTATUS_V, OTMIN_V, NT_V, TF_V, DURATION_V, IFTAR)                                
select CARDNO, SECRETENO, PDATE, INTIME, OUTTIME, OTSTART, 
DURATION, LATEHR, EARLYHR, OTMIN, OTPART, LATESTATUS, 
EARLYSTATUS, 5, YES_NOT, ISLN, SECTIONNM, SHIFT, 
LINENO, FINYEAR, FINMONTH, LATEDED, EARLYDED, OTHR, 
OTHRPART, PSATUS, STATUSDAY, TF, OUTTIME_V, EARLYHR_V, 
EARLYSTATUS_V, OTMIN_V, NT_V, TF_V, DURATION_V, IFTAR from tb_data_master
where finyear=2020
and	  finmonth='December'
and	  cardno in (select cardno from tb_personal_info
				where company='Apparel Plus Ltd.'
				and	  active=0) 







insert into tb_data_master_temp
(CARDNO, SECRETENO, PDATE, INTIME, OUTTIME, OTSTART, 
DURATION, LATEHR, EARLYHR, OTMIN, OTPART, LATESTATUS, 
EARLYSTATUS, COMPANY, YES_NOT, ISLN, SECTIONNM, SHIFT, 
LINENO, FINYEAR, FINMONTH, LATEDED, EARLYDED, OTHR, 
OTHRPART, PSATUS, STATUSDAY, TF, OUTTIME_V, EARLYHR_V, 
EARLYSTATUS_V, OTMIN_V, NT_V, TF_V, DURATION_V, IFTAR)                                
select CARDNO, SECRETENO, PDATE, INTIME, OUTTIME, OTSTART, 
DURATION, LATEHR, EARLYHR, OTMIN, OTPART, LATESTATUS, 
EARLYSTATUS, 5, YES_NOT, ISLN, SECTIONNM, SHIFT, 
LINENO, FINYEAR, FINMONTH, LATEDED, EARLYDED, OTHR, 
OTHRPART, PSATUS, STATUSDAY, TF, OUTTIME_V, EARLYHR_V, 
EARLYSTATUS_V, OTMIN_V, NT_V, TF_V, DURATION_V, IFTAR from tb_data_master_temp
where finyear=2020
and	  finmonth='December'
and	  cardno in (select cardno from tb_personal_info
where company='Apparel Plus Ltd.'
and	  active=0) 



select * from 
(select cardno, count(pdate) com2 from tb_data_master
where company=2
and	  finyear=2020
and	  finmonth='December'
and	  cardno in (select cardno from tb_personal_info
where company='Apparel Plus Ltd.'
and	  active=0)
group by cardno) a,
(select cardno, count(pdate) com5 from tb_data_master
where company=5
and	  finyear=2020
and	  finmonth='December'
and	  cardno in (select cardno from tb_personal_info
where company='Apparel Plus Ltd.'
and	  active=0)
group by cardno) b
where a.cardno=b.cardno






update tb_personal_info info
set info.GROSSSALARY=(select sal.GROSSSAL from tb_month_salary sal
where sal.finyear=2020
	and	  sal.finmonth='October'
	and	  sal.COMPANY='Apparel Plus Limited.'
	and	  sal.cardno=info.cardno)
where company='Apparel Plus Ltd.'
and	  cardno in (select cardno from tb_personal_info
	  		 	where company='Apparel Plus Ltd.')

				select info.* from tb_personal_info info,tb_month_salary sal
where sal.COMPANY='Apparel Plus Limited.'
and	  sal.finyear=2020
and	  sal.finmonth='November'
and	  info.COMPANY='Apparel Plus Ltd.'
and	  sal.GROSSSAL=info.GROSSSALARY
and	  sal.cardno=info.cardno
				
				insert into tb_data_master_temp
(CARDNO, SECRETENO, PDATE, INTIME, OUTTIME, OTSTART, 
DURATION, LATEHR, EARLYHR, OTMIN, OTPART, LATESTATUS, 
EARLYSTATUS, COMPANY, YES_NOT, ISLN, SECTIONNM, SHIFT, 
LINENO, FINYEAR, FINMONTH, LATEDED, EARLYDED, OTHR, 
OTHRPART, PSATUS, STATUSDAY, TF, OUTTIME_V, EARLYHR_V, 
EARLYSTATUS_V, OTMIN_V, NT_V, TF_V, DURATION_V, IFTAR)                                
select CARDNO, SECRETENO, PDATE, INTIME, OUTTIME, OTSTART, 
DURATION, LATEHR, EARLYHR, OTMIN, OTPART, LATESTATUS, 
EARLYSTATUS, 5, YES_NOT, ISLN, SECTIONNM, SHIFT, 
LINENO, FINYEAR, FINMONTH, LATEDED, EARLYDED, OTHR, 
OTHRPART, PSATUS, STATUSDAY, TF, OUTTIME_V, EARLYHR_V, 
EARLYSTATUS_V, OTMIN_V, NT_V, TF_V, DURATION_V, IFTAR from tb_data_master_temp
where finyear=2021
and	  finmonth='January'
and	  cardno in (select cardno from tb_personal_info
				where company='Apparel Plus Ltd.'
				and	  active=0) 
				


insert into TB_DUTY_SCHEDULE_SETUP (DUTYID, COMPANY, SECTION_WORKER, INSTARTTIME, LATESTARTTIME, LASTINTIME, EXITTIME, OTAPPLICABLE, 
SHIFT, WHOLEDAY, OTCOM, PROCESSBY, PROCESSDATE, RAMADAN_STATUS, RAMADAN_BK_TIME, RAMADAN_OT_DED, NTTIME, TFTIME, NT_STATUS, NT_OT_DED)
(select (34+DUTYID), 'Apparel Plus Ltd.', SECTION_WORKER, INSTARTTIME, LATESTARTTIME, LASTINTIME, EXITTIME, OTAPPLICABLE, 
SHIFT, WHOLEDAY, OTCOM, PROCESSBY, PROCESSDATE, RAMADAN_STATUS, RAMADAN_BK_TIME, RAMADAN_OT_DED, NTTIME, TFTIME, NT_STATUS, NT_OT_DED
from TB_DUTY_SCHEDULE_SETUP where company='Apparel Plus Limited.')





insert into TB_LEAVE_DETAILINFO (SLNO, CARDNO, FINYEAR, FINMONTH, LEAVE_TYPE, START_DATE, END_DATE, 
LEAVEDAY, SALDAY, LEAVE_STATUS, PROCESSDATE, UPDATEED, UPDATEBY, COMPANY, REASON, REMARKS)
(select (11794+SLNO), CARDNO, FINYEAR, FINMONTH, LEAVE_TYPE, START_DATE, 
END_DATE, LEAVEDAY, SALDAY, LEAVE_STATUS, PROCESSDATE, UPDATEED, 
UPDATEBY, 'Apparel Plus Ltd.', REASON, REMARKS from TB_LEAVE_DETAILINFO
where finyear=2020
and	  finmonth = 'October'
and	  cardno in (
select cardno from tb_personal_info
where active=0
and company='Apparel Plus Ltd.'))


insert into TB_MATERNITY_LEAVE_DETAIL (SLNO, CARDNO, FINYEAR, FINMONTH, GROSSSAL, PAYAMOUNT, COMPANY, PTNO, WORK_DAY)
select (148+SLNO), CARDNO, FINYEAR, FINMONTH, GROSSSAL, PAYAMOUNT,'Apparel Plus Ltd.', PTNO, WORK_DAY 
from TB_MATERNITY_LEAVE_DETAIL
where finyear=2020
and finmonth='December'
and cardno in (
select cardno from tb_personal_info
where active=0
and company='Apparel Plus Ltd.')
