SELECT INFO.DEPARTMENTNM, INFO.SECTIONNM, INFO.CARDNO, 
INFO.DESIGNATION, COUNT(PRLATE.CARDNO)
FROM TB_PERSONAL_INFO INFO, TB_MONTH_PRESNT_LATE PRLATE
WHERE INFO.COMPANY='Apparel Plus Limited.'
AND	  PRLATE.COMPANY=INFO.COMPANY
AND	  INFO.ACTIVE=0
AND	  INFO.CARDNO=PRLATE.CARDNO
GROUP  BY INFO.DEPARTMENTNM, INFO.SECTIONNM, INFO.CARDNO, 
INFO.DESIGNATION




