SELECT TB_COMPANY_INFO.COMPANY,SECTIONNM,
CARDNO,PDATE,INTIME,OUTTIME,OTMIN
FROM TB_DATA_MASTER
INNER JOIN TB_COMPANY_INFO ON TB_DATA_MASTER.COMPANY=TB_COMPANY_INFO.COMID
WHERE TB_DATA_MASTER.COMPANY IN (SELECT COMID FROM TB_COMPANY_INFO WHERE COMPANY=:VR_COMPANY)
AND FINYEAR=:VR_YEAR
AND FINMONTH=:VR_MONTH
AND PDATE = TO_DATE(:VR_DATES||' 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
AND OTMIN=0
AND OUTTIME >'18:00:00 PM'
AND CARDNO IN (
	SELECT CARDNO 
	FROM TB_PERSONAL_INFO 
	WHERE ACTIVE=0
	AND OTORG='Y'
	)
ORDER BY COMPANY,SECTIONNM