--- late generate 

DECLARE
INTIME_S TB_DATA_MASTER.INTIME%TYPE;
CARDNO_S TB_DATA_MASTER.CARDNO%TYPE;
INTIME_HUR NUMBER:=0;
INTIME_MIN NUMBER:=0;
INTIME_SEC NUMBER:=0;
TEMP_MIN NUMBER:=0;
TEMP_HUR NUMBER:=0;
STR_MIN VARCHAR(50);
STR_HUR VARCHAR(50);
DUCT_NUMBER NUMBER:=:DUC_MIN;

CURSOR EMP_LIST IS
	   (SELECT CARDNO,INTIME FROM TB_DATA_MASTER
	   WHERE COMPANY=2
	   AND FINYEAR =:FIN_YEAR
	   AND FINMONTH=:FIN_MONTH
	   AND PDATE=:P_DATE
	   AND INTIME IS NOT NULL);

BEGIN
OPEN EMP_LIST;
LOOP
	FETCH EMP_LIST INTO CARDNO_S,INTIME_S;
	EXIT WHEN EMP_LIST%NOTFOUND;
	
	INTIME_HUR:=SUBSTR(INTIME_S,1,INSTR(INTIME_S,':')-1);
	INTIME_MIN:=(SUBSTR(INTIME_S,INSTR(INTIME_S,':')+1,INSTR(INTIME_S,':')-1));
	
	IF (INTIME_MIN+DUCT_NUMBER)>59 THEN
	   TEMP_MIN:=(INTIME_MIN+DUCT_NUMBER)-59;
	   TEMP_HUR:=INTIME_HUR+1;
	   
	   	IF TEMP_MIN<10 THEN
	   	  STR_MIN:='0'||TEMP_MIN;
		ELSE
			STR_MIN:=TEMP_MIN;
		END IF;
		
		IF TEMP_HUR<10 THEN
		   STR_HUR:='0'||TEMP_HUR;
		ELSE
			STR_HUR:=TEMP_HUR;
		END IF;
	ELSE
		STR_MIN:=(INTIME_MIN+DUCT_NUMBER);
		
		IF INTIME_HUR<10 THEN
		   STR_HUR:='0'||INTIME_HUR;
		ELSE
			STR_HUR:=TEMP_HUR;
		END IF;
		
	END IF;
	
	INTIME_S:=STR_HUR||':'||STR_MIN||(SUBSTR(INTIME_S,6,11));
	
	UPDATE TB_DATA_MASTER DATA_MST
	SET DATA_MST.INTIME =INTIME_S
	WHERE DATA_MST.PDATE ='7-Mar-2019'
	AND	  DATA_MST.CARDNO=CARDNO_S;
	
	DBMS_OUTPUT.PUT_LINE('CR: '||CARDNO_S||'  NEW: '||STR_HUR||' - '||STR_MIN||'  ORG: '||INTIME_HUR||' - '||INTIME_MIN||'  DUCT: '||DUCT_NUMBER||' FINAL: '||INTIME_S);
	INTIME_S:='';
END LOOP;
CLOSE EMP_LIST;
END;

