SELECT
*
FROM
	TB_DATA_MASTER
	--TB_DATA_MASTER_ARCV
	--TB_DATA_MASTER_ARCV_V
	--TB_DATA_MASTER_TEMP
	--TB_DATA_MASTER_TEMP_ARCV
WHERE
	TB_DATA_MASTER.CARDNO=:CARD
	--AND TB_DATA_MASTER.PDATE=:DATES
	AND TB_DATA_MASTER.FINMONTH=:MONTHS
	--TB_DATA_MASTER_ARCV.CARDNO=:CARD
	--AND TB_DATA_MASTER_ARCV.PDATE=:DATES
	--TB_DATA_MASTER_ARCV_V.CARDNO=:CARD
	--AND TB_DATA_MASTER_ARCV_V.PDATE=:DATES
	--TB_DATA_MASTER_TEMP.CARDNO=:CARD
	--AND TB_DATA_MASTER_TEMP.PDATE=:DATES
	--TB_DATA_MASTER_TEMP_ARCV.CARDNO=:CARD
	--AND TB_DATA_MASTER_TEMP_ARCV.PDATE=:DATES
	
	