DECLARE

IMP_CARDNO TB_JOB_CARD_TEMP.CARDNO%TYPE := :EMP_CARDNO;
IMP_FINMONTH TB_JOB_CARD_TEMP.FINMONTH%TYPE := :FINAL_MONTH;
IMP_FINYEAR TB_JOB_CARD_TEMP.FINYEAR%TYPE := :FINAL_YEAR;
IMP_COMPANY TB_JOB_CARD_TEMP.COMPANY%TYPE := :EMP_COMPANY;
IMP_WK_HOLIDAY TB_JOB_CARD_TEMP.WEEKSTATUS%TYPE := :EMP_WK_HOLIDAY;


C_TOTAL_OTHR NUMBER:=0;
C_PRESENT NUMBER:=0;
C_TOTAL_MONTH NUMBER:=0;
C_WK_END NUMBER:=0;
C_TOTAL_ABSENT NUMBER:=0;
C_HOLIDAY NUMBER:=0;
TEMP_CARDNO TB_PERSONAL_INFO.CARDNO%TYPE;
COUNT INTEGER:=0;

CURSOR C_EMP_LIST IS 
	   SELECT CARDNO FROM TB_PERSONAL_INFO
	   WHERE COMPANY=IMP_COMPANY
	   AND ACTIVE=0;
	   
BEGIN 
OPEN C_EMP_LIST;

LOOP

	FETCH C_EMP_LIST INTO TEMP_CARDNO;
	
		EXIT WHEN C_EMP_LIST%NOTFOUND;
		
		
			SELECT SUM(OTHR) INTO C_TOTAL_OTHR FROM TB_JOB_CARD_TEMP 
			  					   	  WHERE COMPANY=IMP_COMPANY
									  AND FINYEAR=IMP_FINYEAR
									  AND FINMONTH=IMP_FINMONTH
									  AND CARDNO=TEMP_CARDNO;
			--DBMS_OUTPUT.put_line('Total OT: '||C_TOTAL_OTHR);
			
			SELECT COUNT(PSTATUS) INTO C_PRESENT FROM TB_JOB_CARD_TEMP 
			   			 		   	WHERE COMPANY=IMP_COMPANY
									  AND FINYEAR=IMP_FINYEAR
									  AND FINMONTH=IMP_FINMONTH
									  AND CARDNO=TEMP_CARDNO;
			--DBMS_OUTPUT.put_line('Present: '||C_PRESENT);
			
			SELECT COUNT(*) INTO C_TOTAL_MONTH FROM TB_JOB_CARD_TEMP 
			   			 		   	WHERE COMPANY=IMP_COMPANY
									  AND FINYEAR=IMP_FINYEAR
									  AND FINMONTH=IMP_FINMONTH
									  AND CARDNO=TEMP_CARDNO;
			--DBMS_OUTPUT.put_line('Total Month: '||C_TOTAL_MONTH);
			
			SELECT COUNT(*) INTO C_WK_END FROM TB_JOB_CARD_TEMP 
			   			 		   	WHERE COMPANY=IMP_COMPANY
									  AND FINYEAR=IMP_FINYEAR
									  AND FINMONTH=IMP_FINMONTH
									  AND CARDNO=TEMP_CARDNO
									  AND WEEKSTATUS=IMP_WK_HOLIDAY
									  AND PSTATUS IS NULL;
			--DBMS_OUTPUT.put_line('Week End: '||C_WK_END);
			
			C_TOTAL_ABSENT:=(C_TOTAL_MONTH-(C_PRESENT+C_WK_END));
			--DBMS_OUTPUT.put_line('Total Absent: '||C_TOTAL_ABSENT);
			
			SELECT COUNT(*) INTO C_HOLIDAY FROM TB_JOB_CARD_TEMP
					  		 		WHERE COMPANY=IMP_COMPANY
									  AND FINYEAR=IMP_FINYEAR
									  AND FINMONTH=IMP_FINMONTH
									  AND CARDNO=TEMP_CARDNO
									  AND WEEKSTATUS='Gen. Holiday';
									  
			DBMS_OUTPUT.put_line('Cardno: '||TEMP_CARDNO||' Month: '||C_TOTAL_MONTH||' Week End: '||C_WK_END||' Holiday: '||C_HOLIDAY||
								' Present: '||C_PRESENT||' Absent: '||C_TOTAL_ABSENT||' OT: '||C_TOTAL_OTHR);
			DBMS_OUTPUT.PUT_LINE('__________________________________________________________________________________');
						
END LOOP;

CLOSE C_EMP_LIST;

END; 
/