--- see the list which person are promoted
SELECT TB_PRO.CARDNO, TB_PER.CARDNO 
FROM TB_PROMOTION_INFO TB_PRO, TB_PERSONAL_INFO TB_PER
WHERE TB_PRO.COMPANY='SISTER DENIM COMPOSITE LTD.'
AND TB_PER.COMPANY=TB_PRO.COMPANY
AND TB_PRO.PROYEAR=2020
AND TB_PRO.FINMONTH='January'
AND TB_PRO.WORKERTYPE='Staff'
AND TB_PRO.PRO_WORKER_TYPE=TB_PER.WORKERTYPE
AND TB_PRO.CURRDESIGNATION=TB_PRO.PRODESIGNATION 
AND TB_PRO.CARDNO=TB_PER.CARDNO

--- update gross salary and remove promoted salary
UPDATE TB_PERSONAL_INFO TB_PER
SET TB_PER.GROSS_BK = (
	SELECT GROSSSAL_BK FROM TB_PROMOTION_INFO TB_PRO
	WHERE TB_PRO.COMPANY=TB_PER.COMPANY
	AND TB_PRO.PROYEAR=2020
	AND TB_PRO.FINMONTH LIKE DECODE(NVL(:PROMOTION_MONTH,'ALL'),'ALL','%',:PROMOTION_MONTH)
	AND TB_PRO.PRO_WORKER_TYPE=TB_PER.WORKERTYPE
	AND TB_PRO.CURRDESIGNATION=TB_PRO.PRODESIGNATION 
	AND TB_PRO.CARDNO=TB_PER.CARDNO
)
WHERE TB_PER.COMPANY LIKE DECODE(NVL(:COMPANY,'ALL'),'ALL','%',:COMPANY)
AND TB_PER.WORKERTYPE LIKE DECODE(NVL(:WORKER_TYPE,'ALL'),'ALL','%',:WORKER_TYPE)
AND TB_PER.CARDNO IN (
	SELECT TB_PRO.CARDNO
	FROM TB_PROMOTION_INFO TB_PRO
	WHERE TB_PRO.COMPANY LIKE DECODE(NVL(:COMPANY,'ALL'),'ALL','%',:COMPANY)
	AND TB_PRO.PROYEAR LIKE DECODE(NVL(:PROMOTION_YEAR,'ALL'),'ALL','%',:PROMOTION_YEAR)
	AND TB_PRO.FINMONTH LIKE DECODE(NVL(:PROMOTION_MONTH,'ALL'),'ALL','%',:PROMOTION_MONTH)
	AND TB_PRO.WORKERTYPE LIKE DECODE(NVL(:WORKER_TYPE,'ALL'),'ALL','%',:WORKER_TYPE)
	AND TB_PRO.CURRDESIGNATION=TB_PRO.PRODESIGNATION 
)





