
SELECT COUNT_DATA,DATA_LINE,COUNT_PER,PER_LINE FROM
(SELECT COUNT(TB_DATA_MASTER.CARDNO) COUNT_DATA,TB_DATA_MASTER.LINENO DATA_LINE
		FROM TB_DATA_MASTER 
		WHERE PDATE = TO_DATE('02/11/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
		GROUP BY TB_DATA_MASTER.LINENO
),
(SELECT COUNT(TB_PERSONAL_INFO.CARDNO) COUNT_PER,TB_PERSONAL_INFO.LINENO PER_LINE
		FROM TB_PERSONAL_INFO
		WHERE ACTIVE=0
		GROUP BY TB_PERSONAL_INFO.LINENO
)
WHERE DATA_LINE=PER_LINE

SELECT COUNT(CARDNO),LINENO FROM TB_PERSONAL_INFO WHERE ACTIVE=0 GROUP BY LINENO 

SELECT COUNT(CARDNO),LINENO FROM TB_DATA_MASTER WHERE PDATE = TO_DATE('02/11/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS') 
AND SECTIONNM='Admin'
GROUP BY LINENO


SELECT * FROM TB_DATA_MASTER WHERE PDATE=TO_DATE('02/11/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS') 
AND CARDNO IN (SELECT CARDNO FROM TB_PERSONAL_INFO WHERE SECTIONNM='Admin' AND DEPARTMENTNM='Administrator' AND SHIFT='G' AND ACTIVE=0)



SELECT DISTINCT SECTIONNM FROM TB_PERSONAL_INFO WHERE COMPANY='Natural Denims Ltd.'




----------------------------------------------



SELECT PRESENT,
	   DATA_LINE,
	   DATA_SECTION,
	   TOTAL_EMP,
	   PER_LINE,
	   PER_SECTION,
	   PER_DPT FROM
(
SELECT COUNT(TB_DATA_MASTER.CARDNO) PRESENT,
	   TB_DATA_MASTER.LINENO DATA_LINE,
	   TB_DATA_MASTER.SECTIONNM DATA_SECTION
FROM TB_DATA_MASTER 
WHERE PDATE = TO_DATE('02/11/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
AND TB_DATA_MASTER.COMPANY=(
							SELECT COMID 
							FROM TB_COMPANY_INFO
							WHERE COMPANY='Natural Denims Ltd.'
							)
GROUP BY TB_DATA_MASTER.LINENO,
	  	 TB_DATA_MASTER.SECTIONNM
),
(
SELECT COUNT(TB_PERSONAL_INFO.CARDNO) TOTAL_EMP,
	   TB_PERSONAL_INFO.LINENO PER_LINE, 
	   TB_PERSONAL_INFO.SECTIONNM PER_SECTION,
	   TB_PERSONAL_INFO.DEPARTMENTNM PER_DPT
FROM TB_PERSONAL_INFO
WHERE TB_PERSONAL_INFO.ACTIVE=0
AND TB_PERSONAL_INFO.COMPANY='Natural Denims Ltd.'
GROUP BY TB_PERSONAL_INFO.DEPARTMENTNM,
	  TB_PERSONAL_INFO.SECTIONNM,
	  TB_PERSONAL_INFO.LINENO
)
WHERE DATA_LINE=PER_LINE
AND DATA_SECTION=PER_SECTION
