


SELECT * FROM
(
(
	SELECT DT_MASTER.CARDNO,
		   DT_MASTER.INTIME,
		   DT_MASTER.OUTTIME,
		   (DT_MASTER.OTMIN/60) AS OT_HOURS,
		   ROUND((((INFO.GROSSSALARY-1850)/ST_INFO.FIGURE)/208)*2)*(DT_MASTER.OTMIN/60) AS OT_AMOUNT
 	FROM TB_PERSONAL_INFO INFO,TB_SETUP_INFO ST_INFO,TB_DATA_MASTER DT_MASTER
	WHERE DT_MASTER.CARDNO=INFO.CARDNO
	AND ST_INFO.ITEM_NAME='Basic'
	AND ST_INFO.EMP_CATEGORY IN (SELECT WORKERTYPE FROM TB_PERSONAL_INFO WHERE CARDNO=INFO.CARDNO) 
	AND DT_MASTER.PDATE=TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
	AND INFO.ACTIVE=0
	AND INFO.COMPANY='Natural Denims Ltd.'
	AND DT_MASTER.INTIME>='08:00:00 PM'
	AND DT_MASTER.OUTTIME<='23:20:01 PM'
)
UNION
(
 	SELECT 'SUB TOTAL',
		   ' ',
		   ' ',
		   SUM(DT_MASTER.OTMIN/60),
		   ROUND(SUM(((((INFO.GROSSSALARY-1850)/ST_INFO.FIGURE)/208)*2)*(DT_MASTER.OTMIN/60)))
	FROM TB_PERSONAL_INFO INFO,TB_SETUP_INFO ST_INFO,TB_DATA_MASTER DT_MASTER
	WHERE DT_MASTER.CARDNO=INFO.CARDNO
	AND ST_INFO.ITEM_NAME='Basic'
	AND ST_INFO.EMP_CATEGORY IN (SELECT WORKERTYPE FROM TB_PERSONAL_INFO WHERE CARDNO=INFO.CARDNO)
	AND DT_MASTER.PDATE=TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
	AND ACTIVE=0
	AND INFO.COMPANY='Natural Denims Ltd.'
	AND DT_MASTER.INTIME>='08:00:00 PM'
	AND DT_MASTER.OUTTIME<='23:20:01 PM'
)
)
