
CREATE TABLE TB_WINDOWNAME
(
  WINNO  INT(11)
);


CREATE TABLE TB_WEEKLY_HOLIDAY_ALTERNATIVE
(
  SLNO         INT(11),
  PDATE        DATE,
  CARDNO       VARCHAR(15),
  EMPNAME      VARCHAR(250),
  COMPANY      VARCHAR(250),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR(50)
);

CREATE TABLE TB_WEEKLY_HOLIDAY
(
  WEEKID    INT(11),
  FINYEAR   INT(11),
  FINMONTH  VARCHAR(45),
  HOLIDAY   VARCHAR(50),
  COMPANY   VARCHAR(250)
);

CREATE TABLE TB_USER_INFO
(
  USR_ID         INT(11) NOT NULL,
  USER_NAME      VARCHAR(20),
  USER_PASSWORD  VARCHAR(20),
  USER_MODE      VARCHAR(5)
);

CREATE TABLE TB_SHIFT
(
  SHIFTNAME  VARCHAR(20),
  SHIFT      VARCHAR(5)
)

CREATE TABLE TB_SETUP_INFO
(
  ITEM_NAME     VARCHAR(25),
  FIGURE        NUMBER,
  EMP_CATEGORY  VARCHAR2(18),
  SL            INT(11)
)

CREATE TABLE TB_SECTION_INFO
(
  SECID            INT(11),
  DEPARTTMENTNM    VARCHAR(100),
  SECTIONNM        VARCHAR(100),
  SECTIONADDRESS   VARCHAR(150),
  SECTIONPHONE     NUMBER,
  WEBADDRESS       VARCHAR(100),
  PROCESSBY        VARCHAR(30),
  PROCESSDATE      DATE,
  SEC_NAME_BANGLA  VARCHAR(100)
);

CREATE TABLE TB_SALGRADE
(
  GRDID     INT(11),
  GRADE     VARCHAR(10),
  L_SALARY  INT(11),
  H_SALARY  INT(11)
);

CREATE TABLE TB_SALARY_HALF_SETUP
(
  FINYEAR     INT(11),
  FINMONTH    VARCHAR(25),
  WORKERTYPE  VARCHAR(50),
  PER         INT(11),
  COMPANY     VARCHAR(250)
);

CREATE TABLE TB_PROCESS_PRIVILEGES
(
  PRO_ID     INT(11)                      NOT NULL,
  USER_NAME  VARCHAR(20)                  NOT NULL,
  USER_MODE  VARCHAR(5)                   NOT NULL
);

CREATE TABLE TB_PROCESS_NAME
(
  PROCESSNAME  VARCHAR(180)               NOT NULL,
  PRO_ID       INT(11),
  FILE_PATH    VARCHAR(220)
);

CREATE TABLE TB_PF_Y_N
(
  FUNDID       INT(11),
  EMPNO        VARCHAR(15),
  DEPARTMENT   VARCHAR(200),
  EMPNAME      VARCHAR(200),
  JOININGDATE  DATE,
  PFSTARTDATE  DATE,
  PF_Y_N       VARCHAR(5),
  OPENINGBAL   INT(11),
  LOANAMT      INT(11),
  LOANDATE     DATE,
  BALANCE      INT(11),
  UPDATEDDATE  DATE,
  UPDATEBY     VARCHAR(50),
  COMPANY      VARCHAR(255)
);

CREATE TABLE TB_PF_YEARLY_ITERESTAMT
(
  SLNO         INT(11),
  FINYEAR      INT(11),
  EMPNO        VARCHAR(15),
  EMPNAME      VARCHAR(250),
  DEPARTMENT   VARCHAR(150),
  AMOUNT       INT(11),
  PROCESSDATE  DATE,
  COMPANY      VARCHAR(255)
);

CREATE TABLE TB_PF_YEARLY_INTSETUP
(
  INTID       INT(11),
  FINYEAR     INT(11),
  PERCENTAGE  INT(11)
);

CREATE TABLE TB_PF_SETUP
(
  SETID       INT(11),
  FINYEAR     INT(11),
  FINMONTH    VARCHAR(20),
  CELLFIELD   VARCHAR(25),
  PERCENTAGE  INT(11)
);

CREATE TABLE TB_PF_DETAILS_AMT
(
  FINYEAR        INT(11),
  EMPNO          VARCHAR(15),
  EMPNAME        VARCHAR(250),
  DEPARTMENT     VARCHAR(150),
  OWNCONTRI      INT(11),
  COMCONTRI      INT(11),
  PERCENTAGE     INT(11),
  PERCENTAMT     INT(11),
  INTERESTAMT    INT(11),
  ADVANCEORLOAN  INT(11),
  OPENBALANCE    INT(11),
  TOTALPFAMT     INT(11),
  SDUTATION      INT(11),
  PROCESSDATE    DATE,
  PROCESSBY      VARCHAR(25),
  COMPANY        VARCHAR(255),
  Y_N            INT(11)
);

CREATE TABLE TB_PERSONAL_INFO_BANGLA
(
  EMPID         INT(11),
  CARDNO        VARCHAR(15)               NOT NULL,
  EMPNAME       VARCHAR(200),
  DESIGNATION   VARCHAR(150),
  JOINING_DATE  DATE,
  DEPARTMENTNM  VARCHAR(150),
  SECTIONNM     VARCHAR(110),
  SALARYGRD     VARCHAR(5),
  BLOODGROUP    VARCHAR(5),
  COMPANY       VARCHAR(250),
  ECOMPANY      VARCHAR(250),
  PROCESSBY     VARCHAR(45),
  PROCESSDATE   DATE
);

COMMENT ON TABLE TB_PERSONAL_INFO_BANGLA IS 'card no = ''12624''';


CREATE TABLE TB_PERFORMANCE_YEARLY_AMT
(
  YRID          INT(11),
  EMPNO         VARCHAR(15),
  EMPNAME       VARCHAR(215),
  FINYEAR       INT(11),
  AVGGRADE      VARCHAR(5),
  AVGMARK       INT(11),
  FINALMARK     INT(11),
  GROSSSAL      INT(11),
  INCREMENTAMT  INT(11),
  PROCESSDATE   DATE,
  PROCESSBY     VARCHAR(25),
  COMPANY       VARCHAR(215)
);


CREATE TABLE TB_PERFORMANCE_SETUP
(
  GRDPOINT_CRITIRIA  VARCHAR(50)
)


CREATE TABLE TB_PERFORMANCE_MONTHLY
(
  PERID       INT(11),
  EMPNO       VARCHAR(15),
  EMPNAME     VARCHAR(250),
  FINYEAR     INT(11),
  P1GRD       VARCHAR(3),
  P1POINT     INT(11)                            DEFAULT 0,
  P2GRD       VARCHAR(3),
  P2POINT     INT(11)                            DEFAULT 0,
  P3GRD       VARCHAR(3),
  P3POINT     INT(11)                            DEFAULT 0,
  P4GRD       VARCHAR(3),
  P4POINT     INT(11)                            DEFAULT 0,
  P5GRD       VARCHAR(3),
  P5POINT     INT(11)                            DEFAULT 0,
  P6GRD       VARCHAR(3),
  P6POINT     INT(11)                            DEFAULT 0,
  P7GRD       VARCHAR(3),
  P7POINT     INT(11)                            DEFAULT 0,
  COMPANY     VARCHAR(215),
  SPDED       INT(11)                            DEFAULT 0,
  ADJUSTMENT  INT(11)                            DEFAULT 0,
  LASTINCR    INT(11)                            DEFAULT 0,
  YRINCR      INT(11)                            DEFAULT 0
);

CREATE TABLE TB_PERFORMANCE_INCRE_PERCENT
(
  YRID           INT(11),
  FINYEAR        INT(11),
  GRADE          VARCHAR(5),
  GRADEMARK      INT(11),
  PERCENT        INT(11),
  COMPANY        VARCHA2(250),
  GRADEMARK_MAX  INT(11)
);


CREATE TABLE TB_PERFORMANCE_INCRE_AMT
(
  YRID        INT(11),
  EMPNO       VARCHAR(15),
  EMPNAME     VARCHAR(150),
  DEPARTMENT  VARCHAR(150),
  FINYEAR     INT(11),
  GRADE       VARCHAR(5),
  GRADEMARK   INT(11),
  AMOUNT      INT(11),
  COMPANY     VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERFORMANCE_GRADE
(
  GRDPOINT_CRITIRIA  VARCHAR2(50 BYTE),
  GRADE              VARCHAR2(3 BYTE),
  GRADE_MARK         NUMBER,
  MIN_MARKS          NUMBER,
  MAX_MARKS          NUMBER,
  MARK_AMT           NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_SALARY_STAFF
(
  FINYEAR          NUMBER,
  FINMONTH         VARCHAR2(15 BYTE),
  CARDNO           VARCHAR2(15 BYTE),
  EMPNAME          VARCHAR2(150 BYTE),
  GROSSSAL         NUMBER(15,2),
  BASICSAL         NUMBER(15,2),
  HOUSERENT        NUMBER(15,2),
  MEDICAL          NUMBER(15,2),
  TRANSPORT        NUMBER(15,2),
  OTHERALLOW       NUMBER,
  ATTBONUS         NUMBER,
  ARREAR_AMT       NUMBER(15,2),
  PFUND            NUMBER(15,2),
  ABSENT_DEDUC     NUMBER(15,2),
  ADVANCE_DEDUC    NUMBER(15,2),
  HALF_DUTY_DEDUC  NUMBER,
  LUNCH_BILL       NUMBER,
  TAXDEDUCTION     NUMBER(15,2),
  STAMP            NUMBER(15,2),
  NETPAYMENT       NUMBER(15,2),
  NT_BILL          NUMBER,
  EXTRA_BILL       NUMBER,
  TOTALDAY         NUMBER,
  TOTALPRESENT     NUMBER,
  TOTALABSENT      NUMBER,
  TOTALLEAVE       NUMBER,
  COMPANY          VARCHAR2(200 BYTE),
  PROCESSDATE      DATE,
  TOTAL_SALARY     NUMBER,
  SALID            NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_PRESNT_LATE
(
  CARDNO      VARCHAR2(25 BYTE),
  D1          VARCHAR2(3 BYTE),
  D2          VARCHAR2(3 BYTE),
  D3          VARCHAR2(3 BYTE),
  D4          VARCHAR2(3 BYTE),
  D5          VARCHAR2(3 BYTE),
  D6          VARCHAR2(3 BYTE),
  D7          VARCHAR2(3 BYTE),
  D8          VARCHAR2(3 BYTE),
  D9          VARCHAR2(3 BYTE),
  D10         VARCHAR2(3 BYTE),
  D11         VARCHAR2(3 BYTE),
  D12         VARCHAR2(3 BYTE),
  D13         VARCHAR2(3 BYTE),
  D14         VARCHAR2(3 BYTE),
  D15         VARCHAR2(3 BYTE),
  D16         VARCHAR2(3 BYTE),
  D17         VARCHAR2(3 BYTE),
  D18         VARCHAR2(3 BYTE),
  D19         VARCHAR2(3 BYTE),
  D20         VARCHAR2(3 BYTE),
  D21         VARCHAR2(3 BYTE),
  D22         VARCHAR2(3 BYTE),
  D23         VARCHAR2(3 BYTE),
  D24         VARCHAR2(3 BYTE),
  D25         VARCHAR2(3 BYTE),
  D26         VARCHAR2(3 BYTE),
  D27         VARCHAR2(3 BYTE),
  D28         VARCHAR2(3 BYTE),
  D29         VARCHAR2(3 BYTE),
  D30         VARCHAR2(3 BYTE),
  D31         VARCHAR2(3 BYTE),
  SECTIONMNM  VARCHAR2(100 BYTE),
  LINENO      VARCHAR2(55 BYTE),
  COMPANY     VARCHAR2(200 BYTE),
  FINMONTH    VARCHAR2(15 BYTE),
  FINYEAR     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_GENERAL_NOOFHOLIDAY
(
  NOOFDAY   NUMBER,
  FINYEAR   NUMBER,
  FINMONTH  VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_GENERAL_MONTHDAY
(
  FINYEAR   NUMBER,
  FINMONTH  VARCHAR2(15 BYTE),
  DAYTYPE   VARCHAR2(15 BYTE),
  NOOFDAY   NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_GENERALHOLIDAY
(
  SLNO      NUMBER,
  FINYEAR   NUMBER,
  FINMONTH  VARCHAR2(12 BYTE),
  S_DATE    DATE,
  E_DATE    DATE,
  REASON    VARCHAR2(50 BYTE),
  NODAY     NUMBER                              DEFAULT 0,
  SHIFT     VARCHAR2(3 BYTE),
  COMPANY   VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_EXTRAOT_DUTY
(
  CARDNO         VARCHAR2(15 BYTE),
  FINYEAR        NUMBER,
  FINMONTH       VARCHAR2(15 BYTE),
  OTHR           NUMBER,
  OTHR2          NUMBER,
  OTHRWEEK       NUMBER,
  OTHRHOLI       NUMBER,
  CONVERTDAY_NO  NUMBER,
  HOLIDAY_NO     NUMBER,
  TOTALHOUR      NUMBER,
  PROCESSDATE    DATE,
  COMPANY        VARCHAR2(250 BYTE),
  NT_DAY         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_EMP_OT
(
  CARDNO    VARCHAR2(15 BYTE),
  EMPNAME   VARCHAR2(180 BYTE),
  OTHR      NUMBER,
  OTHRPART  NUMBER,
  FINYEAR   NUMBER,
  FINMONTH  VARCHAR2(15 BYTE),
  COMPANY   VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_CONVERT_OTDAY
(
  SLNO      NUMBER,
  FINYEAR   NUMBER,
  FINMONTH  VARCHAR2(12 BYTE),
  S_DATE    DATE,
  E_DATE    DATE,
  REASON    VARCHAR2(50 BYTE),
  COMPANY   VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_CONVERT_GENERALDAY
(
  SLNO      NUMBER,
  FINYEAR   NUMBER,
  FINMONTH  VARCHAR2(12 BYTE),
  S_DATE    DATE,
  E_DATE    DATE,
  REASON    VARCHAR2(50 BYTE),
  COMPANY   VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTHLY_ATTEND_SUMMARY
(
  SLNO         NUMBER,
  PDATE        DATE,
  TOTALEMP     NUMBER,
  TOTALPRSNT   NUMBER,
  WORKERPRSNT  NUMBER,
  STAFFPRSNT   NUMBER,
  FINCONTRACT  NUMBER,
  SEWCONTRACT  NUMBER,
  CUTCONTRACT  NUMBER,
  NEWJOIN      NUMBER,
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE),
  COMPANY      VARCHAR2(250 BYTE),
  PYEAR        NUMBER,
  PMONTH       VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH
(
  SLNO        NUMBER,
  MONTH_NAME  VARCHAR2(15 BYTE),
  MONTH_DAY   NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MANUAL_SUMMARY
(
  SLNO         NUMBER,
  PDATE        DATE,
  FINCONTRACT  NUMBER,
  SEWCONTRACT  NUMBER,
  CUTCONTRACT  NUMBER,
  NEWJOIN      NUMBER,
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE),
  COMPANY      VARCHAR2(250 BYTE),
  REMARKS      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MANUAL_ATTENDENCE
(
  CARDNO       VARCHAR2(15 BYTE),
  SECRETENO    VARCHAR2(15 BYTE),
  PDATE        DATE,
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  OTHR         NUMBER,
  OTHRPART     NUMBER,
  STATUS       VARCHAR2(15 BYTE),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          640K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_LEAVETYPE
(
  SLNO    NUMBER,
  L_TYPE  VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_JOB_CARD
(
  CARDNO       VARCHAR2(15 BYTE),
  EMPNAME      VARCHAR2(200 BYTE),
  DESIGNATION  VARCHAR2(150 BYTE),
  SECTIONNM    VARCHAR2(100 BYTE),
  JOININGDATE  DATE,
  GROSSSAL     NUMBER                           DEFAULT 0,
  MONTHDATE    DATE,
  WEEKSTATUS   VARCHAR2(20 BYTE),
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  OTHR         NUMBER                           DEFAULT 0,
  LATESTATUS   VARCHAR2(10 BYTE),
  OFFDAY       VARCHAR2(15 BYTE),
  PSTATUS      VARCHAR2(5 BYTE),
  DURATION     VARCHAR2(5 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(15 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_IDCARD_MULTIPLE
(
  CARDNO   VARCHAR2(15 BYTE)                    NOT NULL,
  COMPANY  VARCHAR2(255 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_GRATUITY_DETAILS_AMT
(
  EMPNO        VARCHAR2(15 BYTE),
  EMPNAME      VARCHAR2(150 BYTE),
  DEPARTMENT   VARCHAR2(150 BYTE),
  GROSSSAL     NUMBER,
  BASICSAL     NUMBER,
  JOININGDATE  DATE,
  RESIGNDATE   DATE,
  PERIOD       VARCHAR2(20 BYTE),
  NOOFBASIC    NUMBER,
  GRATUITYAMT  NUMBER(20,2),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(25 BYTE),
  COMPANY      VARCHAR2(255 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_PUNISHMENT_RECORD
(
  SLNO         NUMBER,
  CARDNO       VARCHAR2(15 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(25 BYTE),
  PDATE        DATE,
  PUNISHMENT   VARCHAR2(40 BYTE),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE),
  REMARKS      VARCHAR2(250 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_LAUNCH_BILL
(
  SLNO           NUMBER,
  CARDNO         VARCHAR2(15 BYTE),
  FINYEAR        NUMBER,
  FINMONTH       VARCHAR2(25 BYTE),
  LAUNCH_AMOUNT  NUMBER,
  PROCESSDATE    DATE,
  PROCESSBY      VARCHAR2(50 BYTE),
  COMPANY        VARCHAR2(250 BYTE),
  STATUS         VARCHAR2(20 BYTE),
  LUNCH_DATE     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_LATE_INFO
(
  SLNO         NUMBER,
  CARDNO       VARCHAR2(15 BYTE),
  PDATE        DATE,
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  DURATION     VARCHAR2(6 BYTE),
  LATEHR       VARCHAR2(8 BYTE),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_HALF_DUTY
(
  SLNO         NUMBER,
  CARDNO       VARCHAR2(15 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(25 BYTE),
  HRS          NUMBER,
  AMOUNT       NUMBER,
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE),
  REMARKS      VARCHAR2(150 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_DEDUCTION_BILL
(
  SLNO         NUMBER,
  CARDNO       VARCHAR2(15 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(25 BYTE),
  AMOUNT       NUMBER,
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE),
  REMARKS      VARCHAR2(150 BYTE),
  COMPANY      VARCHAR2(250 BYTE),
  STATUS       VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          576K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_CARD_CHANGE
(
  CARDNO       VARCHAR2(15 BYTE),
  CHANGECARD   VARCHAR2(15 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(25 BYTE),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(35 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_ABSENT_DAYS
(
  CARDNO   VARCHAR2(15 BYTE),
  PDATE    DATE,
  COMPANY  VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMPLOYEECATEGORY
(
  EMPID         NUMBER,
  EMPLOYEETYPE  VARCHAR2(100 BYTE),
  WORKERTYPE    VARCHAR2(35 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DUTY_SCHEDULE_SETUP
(
  DUTYID          NUMBER,
  COMPANY         VARCHAR2(255 BYTE),
  SECTION_WORKER  VARCHAR2(50 BYTE),
  INSTARTTIME     DATE,
  LATESTARTTIME   DATE,
  LASTINTIME      DATE,
  EXITTIME        DATE,
  OTAPPLICABLE    VARCHAR2(3 BYTE),
  SHIFT           VARCHAR2(3 BYTE),
  WHOLEDAY        NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DESIGNATION_INFO
(
  DESID               NUMBER,
  DESIGNATION         VARCHAR2(100 BYTE),
  EMPLOYEETYPE        VARCHAR2(30 BYTE),
  SALGRADE            VARCHAR2(10 BYTE),
  NT_AMOUNT           NUMBER,
  ATN_BONUS           NUMBER,
  HOLI_AMOUNT         NUMBER,
  EXTRA_ALLOW         NUMBER,
  HOLIDAY_BILL        NUMBER,
  HOLIDAY_STATUS      VARCHAR2(3 BYTE),
  FESTIVAL_BILL       NUMBER,
  FESTIVAL_STATUS     VARCHAR2(3 BYTE),
  WEEKLY_DAY          VARCHAR2(15 BYTE),
  DESIGNATION_BANGLA  VARCHAR2(100 BYTE),
  PROCESSBY           VARCHAR2(25 BYTE),
  PROCESSDATE         DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DEPARTMENT_INFO
(
  DEPTID            NUMBER,
  DEPT_NAME         VARCHAR2(100 BYTE),
  DEPT_HEAD         VARCHAR2(100 BYTE),
  DEPT_HEAD_NAME    VARCHAR2(255 BYTE),
  DEPT_ADDRESS      VARCHAR2(100 BYTE),
  WEB_ADDRESS       VARCHAR2(100 BYTE),
  PHONE_OFF         NUMBER,
  PROCESSBY         VARCHAR2(25 BYTE),
  PROCESSDATE       DATE,
  DEPT_NAME_BANGLA  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DENOMINATION_INFO
(
  CARDNO     VARCHAR2(15 BYTE),
  SECTIONNM  VARCHAR2(150 BYTE),
  PANCHO     NUMBER,
  AKSHO      NUMBER,
  PANCHASH   NUMBER,
  BISH       NUMBER,
  DASH       NUMBER,
  PANCH      NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_LOAD
(
  MACHINENO  VARCHAR2(20 BYTE),
  SECRETENO  VARCHAR2(15 BYTE),
  DATADATE   VARCHAR2(15 BYTE),
  DATATIME   VARCHAR2(15 BYTE),
  STATUS     VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_IN_TEMP
(
  MACHINENO  VARCHAR2(20 BYTE),
  SECRETENO  VARCHAR2(15 BYTE),
  DATADATE   DATE,
  DATATIME   VARCHAR2(15 BYTE),
  STATUS     VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_IN
(
  MACHINENO  VARCHAR2(20 BYTE),
  SECRETENO  VARCHAR2(15 BYTE),
  DATADATE   DATE,
  DATATIME   VARCHAR2(15 BYTE),
  STATUS     VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_COMPANY_INFO
(
  COMID           NUMBER,
  COMPANY         VARCHAR2(255 BYTE),
  ADDRESS         VARCHAR2(255 BYTE),
  ADDRESS1        VARCHAR2(255 BYTE),
  UNIT            VARCHAR2(255 BYTE),
  HRSIGN_WORKER   BLOB,
  HRSIGN_STAFF    BLOB,
  COMLOGO         BLOB,
  ISOLOGO         BLOB,
  COMPANY_BANGLA  VARCHAR2(255 BYTE),
  HR_HEAD_NAME    VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (ISOLOGO) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB (COMLOGO) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB (HRSIGN_STAFF) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB (HRSIGN_WORKER) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_BONUS_SETUP
(
  BONUS_NAME            VARCHAR2(20 BYTE),
  BONUS_EMP_TYPE        VARCHAR2(15 BYTE),
  BONUS_MIN_DAYS        NUMBER,
  BONUS_MAX_DAYS        NUMBER,
  BONUS_PERCENT         NUMBER,
  BONUS_AMOUNT          NUMBER                  DEFAULT 0,
  BONUS_YEAR            VARCHAR2(4 BYTE),
  BONUS_MONTH           VARCHAR2(15 BYTE),
  BONUS_ON_B_OR_G       CHAR(1 BYTE)            DEFAULT 'B',
  BONUS_APPLICABLE_Y_N  CHAR(1 BYTE),
  NUMBER_OF_BONUS       NUMBER                  DEFAULT 1
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_ADVANCEORLOAN_INFO
(
  SLNO         NUMBER,
  COMPANY      VARCHAR2(255 BYTE),
  LOANNO       VARCHAR2(30 BYTE),
  CARDNO       VARCHAR2(15 BYTE),
  LOANYEAR     NUMBER,
  LOANMONTH    VARCHAR2(15 BYTE),
  DUDUCYEAR    NUMBER,
  DEDUCMONTH   VARCHAR2(15 BYTE),
  LOANAMOUNT   NUMBER(20,2),
  DUDUCAMOUNT  NUMBER(20,2),
  BALAMOUNT    NUMBER(20,2),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE QUEST_COM_USER_PRIVILEGES
(
  PRODUCT_ID       NUMBER                       NOT NULL,
  USER_ID          NUMBER                       NOT NULL,
  PRIVILEGE_ID     VARCHAR2(60 BYTE)            NOT NULL,
  PRIVILEGE_LEVEL  VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE QUEST_COM_USERS
(
  USER_ID              NUMBER                   NOT NULL,
  PRODUCT_ID           NUMBER                   NOT NULL,
  AUTHORIZATION_LEVEL  VARCHAR2(60 BYTE),
  INSTALL_USER         VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE QUEST_COM_PRODUCT_PRIVS
(
  PRODUCT_ID             NUMBER                 NOT NULL,
  PRIVILEGE_ID           VARCHAR2(60 BYTE)      NOT NULL,
  PRIVILEGE_DESCRIPTION  VARCHAR2(256 BYTE)     NOT NULL,
  VALIDATION_ROUTINE     VARCHAR2(2000 BYTE),
  PRIVILEGE_LEVEL        VARCHAR2(256 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE QUEST_COM_PRODUCTS_USED_BY
(
  PRODUCT_ID          NUMBER                    NOT NULL,
  USED_BY_PRODUCT_ID  NUMBER                    NOT NULL,
  PRODUCT_VERSION     VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE QUEST_COM_PRODUCTS
(
  PRODUCT_ID                NUMBER              NOT NULL,
  PRODUCT_NAME              VARCHAR2(30 BYTE)   NOT NULL,
  PRODUCT_PREFIX            VARCHAR2(8 BYTE)    NOT NULL,
  INSTALL_USER              VARCHAR2(30 BYTE)   NOT NULL,
  GRANT_PROCEDURE           VARCHAR2(2000 BYTE),
  REVOKE_PROCEDURE          VARCHAR2(2000 BYTE),
  PRODUCT_VERSION           VARCHAR2(20 BYTE),
  DEINSTALL_SCRIPT          LONG,
  GRANT_PRIV_PROCEDURE      VARCHAR2(2000 BYTE),
  REVOKE_PRIV_PROCEDURE     VARCHAR2(2000 BYTE),
  INSTALLED_BY              VARCHAR2(30 BYTE),
  PRODUCT_SCHEMA_VERSION    VARCHAR2(20 BYTE),
  PRODUCT_BASE_VERSION      VARCHAR2(20 BYTE),
  STAND_ALONE_PRODUCT_FLAG  VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_COMPANY_NAME
(
  COMPANYNAME  VARCHAR2(200 BYTE),
  WELCOMELOGO  BLOB,
  SIGNATURE    BLOB,
  ID           NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (SIGNATURE) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB (WELCOMELOGO) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_HOLIDAY_CHANGE
(
  SLNO            NUMBER,
  CARDNO          VARCHAR2(15 BYTE),
  EXIST_HOLIDAY   VARCHAR2(15 BYTE),
  CHANGE_HOLIDAY  VARCHAR2(15 BYTE),
  EFFECTIVE_DATE  DATE,
  FINMONTH        VARCHAR2(15 BYTE),
  FINYEAR         NUMBER,
  COMPANY         VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_INFO_PROCESS
(
  EMPID         NUMBER,
  CARDNO        VARCHAR2(15 BYTE),
  PROCESS_NAME  VARCHAR2(99 BYTE),
  COMPANY       VARCHAR2(250 BYTE),
  PROCESSBY     VARCHAR2(45 BYTE),
  PROCESSDATE   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_EMP_PROCESS
(
  PROCESS_NAME  VARCHAR2(99 BYTE),
  COMPANY       VARCHAR2(250 BYTE),
  PROCESSBY     VARCHAR2(45 BYTE),
  PROCESSDATE   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_RESIGNATION_INFO
(
  REGID             NUMBER,
  CARDNO            VARCHAR2(15 BYTE),
  DEPARTMENT        VARCHAR2(200 BYTE),
  EMPNAME           VARCHAR2(200 BYTE),
  DESIGNATION       VARCHAR2(200 BYTE),
  JOININGDATE       DATE,
  SALARY            NUMBER,
  RESIGDATE         DATE,
  PICTURE           BLOB,
  PRESENTADDRESS    VARCHAR2(255 BYTE),
  PERMANENTADDRESS  VARCHAR2(255 BYTE),
  COMPANY           VARCHAR2(255 BYTE),
  REMARKS           VARCHAR2(255 BYTE),
  UPDATE_DATE       DATE,
  UPDATE_BY         VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (PICTURE) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PROMOTION_INFO
(
  SLNO             NUMBER,
  PROYEAR          NUMBER,
  CARDNO           VARCHAR2(15 BYTE),
  EMPNAME          VARCHAR2(250 BYTE),
  JOININGDATE      DATE,
  CURRDESIGNATION  VARCHAR2(200 BYTE),
  PRODESIGNATION   VARCHAR2(200 BYTE),
  CURRSALARY       NUMBER,
  PROSALARY        NUMBER,
  SALARYGRD        VARCHAR2(10 BYTE),
  EFFECTIVEDATE    DATE,
  WORKERTYPE       VARCHAR2(100 BYTE),
  COMPANY          VARCHAR2(250 BYTE),
  REMARKS          VARCHAR2(255 BYTE),
  FINMONTH         VARCHAR2(20 BYTE),
  DEDUC_AMOUNT     NUMBER,
  EXIST_SALGRD     VARCHAR2(10 BYTE),
  CHANGE_SALGRD    VARCHAR2(10 BYTE),
  UPDATE_DATE      DATE,
  UPDATE_BY        VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PF_MONTHLY_AMT
(
  AMTID          NUMBER,
  FINYEAR        NUMBER,
  FINMONTH       VARCHAR2(20 BYTE),
  EMPNO          VARCHAR2(15 BYTE),
  OWNCONTRI      NUMBER,
  COMPANYCONTRI  NUMBER,
  COMPANY        VARCHAR2(240 BYTE),
  PDATE          DATE,
  PUSER          VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERFORMANCE_YEARLY
(
  SLNO              NUMBER,
  CARDNO            VARCHAR2(15 BYTE),
  ABSNT_DAY         NUMBER,
  ABSNT_POINT       NUMBER(15,2),
  ATTN_BONUS        NUMBER,
  ATTN_BONUS_POINT  NUMBER(15,2),
  SPECIAL_BONUS     NUMBER(15,2),
  SKILL_GRADE       VARCHAR2(10 BYTE),
  SKILL_BONUS       NUMBER(15,2),
  JULY              VARCHAR2(15 BYTE),
  AUGUST            VARCHAR2(15 BYTE),
  SEPTEMBER         VARCHAR2(15 BYTE),
  OCTOBER           VARCHAR2(15 BYTE),
  NOVEMBER          VARCHAR2(15 BYTE),
  DECEMBER          VARCHAR2(15 BYTE),
  JANUARY           VARCHAR2(15 BYTE),
  FEBRUARY          VARCHAR2(15 BYTE),
  MARCH             VARCHAR2(15 BYTE),
  APRIL             VARCHAR2(15 BYTE),
  MAY               VARCHAR2(15 BYTE),
  JUNE              VARCHAR2(15 BYTE),
  MONTH_SAL_NO      NUMBER,
  MONTH_SAL_POINT   NUMBER(15,2),
  EID_FETTAR_DAY    NUMBER,
  EID_AZHA_DAY      NUMBER,
  EID_DAY_NO        NUMBER,
  EID_DAY_POINT     NUMBER(15,2),
  SPECIAL_DPOINT    NUMBER(15,2),
  TOTAL_DPOINT      NUMBER(15,2),
  P1_POINT          NUMBER,
  P2_POINT          NUMBER,
  P3_POINT          NUMBER,
  P4_POINT          NUMBER,
  P5_POINT          NUMBER,
  P6_POINT          NUMBER,
  P7_POINT          NUMBER,
  TOTAL_SCROR       NUMBER(15,2),
  PERCENT_GRADE     NUMBER,
  GRADE             VARCHAR2(3 BYTE),
  INCR_AMOUNT       NUMBER,
  ATTN_BONUS_AMT    NUMBER,
  SP_BONUS_AMT      NUMBER,
  SKILL_BONUS_AMT   NUMBER,
  ADJECT_AMT        NUMBER,
  TOTAL_INCR_AMT    NUMBER,
  PERCENT_INCR_AMT  NUMBER,
  GROSS_SAL         NUMBER,
  NEW_GROSS_SAL     NUMBER,
  COMPANY           VARCHAR2(255 BYTE),
  FINYEAR           NUMBER,
  LASTINCR          NUMBER                      DEFAULT 0,
  PROINCR           NUMBER                      DEFAULT 0,
  LASTINCR_DATE     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_OT_DAYWISE
(
  CARDNO    VARCHAR2(15 BYTE),
  D1        NUMBER,
  D2        NUMBER,
  D3        NUMBER,
  D4        NUMBER,
  D5        NUMBER,
  D6        NUMBER,
  D7        NUMBER,
  D8        NUMBER,
  D9        NUMBER,
  D10       NUMBER,
  D11       NUMBER,
  D12       NUMBER,
  D13       NUMBER,
  D14       NUMBER,
  D15       NUMBER,
  D16       NUMBER,
  D17       NUMBER,
  D18       NUMBER,
  D19       NUMBER,
  D20       NUMBER,
  D21       NUMBER,
  D22       NUMBER,
  D23       NUMBER,
  D24       NUMBER,
  D25       NUMBER,
  D26       NUMBER,
  D27       NUMBER,
  D28       NUMBER,
  D29       NUMBER,
  D30       NUMBER,
  D31       NUMBER,
  TOTAL     NUMBER(30,2),
  COMPANY   VARCHAR2(250 BYTE),
  FINMONTH  VARCHAR2(15 BYTE),
  FINYEAR   VARCHAR2(4 BYTE),
  SDATE     DATE,
  EDATE     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_GENERAL_DAYADDCUT
(
  EMPID        NUMBER,
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(15 BYTE),
  CARDNO       VARCHAR2(15 BYTE),
  NOOFDAY      NUMBER,
  GENERAL_Y_N  VARCHAR2(3 BYTE),
  G_DAY        NUMBER,
  PROCESSDATE  DATE,
  UPDATEBY     VARCHAR2(20 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_LEAVE_SUMMARY
(
  FINYEAR       NUMBER,
  CARDNO        VARCHAR2(15 BYTE),
  DEPARTMENTNM  VARCHAR2(150 BYTE),
  SECTIONNM     VARCHAR2(100 BYTE),
  EMPNAME       VARCHAR2(200 BYTE),
  JOININGDATE   DATE,
  CASUALLEAVE   NUMBER,
  AVAILCASUAL   NUMBER,
  MEDICALLEAVE  NUMBER,
  AVAILMEDICAL  NUMBER,
  EARNEDLEAVE   NUMBER,
  AVAILEARNED   NUMBER,
  COMPENLEAVE   NUMBER,
  AVAILCOMPEN   NUMBER,
  PASTEARNE     NUMBER,
  PROCESSDATE   DATE,
  PROCESSBY     VARCHAR2(50 BYTE),
  COMPANY       VARCHAR2(255 BYTE),
  YES_NOT       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_LEAVE_MASTERINFO
(
  LEAVEID       NUMBER,
  FINYEAR       NUMBER,
  CARDNO        VARCHAR2(15 BYTE),
  DEPARTMENTNM  VARCHAR2(150 BYTE),
  CA_LEAVE      NUMBER,
  TAKEN_CA      NUMBER,
  AVAL_CA       NUMBER,
  MED_LEAVE     NUMBER,
  TAKEN_MED     NUMBER,
  AVAL_MED      NUMBER,
  EAR_LEAVE     NUMBER,
  TAKEN_EAR     NUMBER,
  AVAL_EAR      NUMBER,
  COM_LEAVE     NUMBER,
  TAKEN_COM     NUMBER,
  AVAL_COM      NUMBER,
  OTHER_LEAVE   NUMBER,
  TAKEN_OTHER   NUMBER,
  AVAL_OTHER    NUMBER,
  COMPANY       VARCHAR2(255 BYTE),
  UPDATEED      DATE,
  UPDATEBY      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_LEAVE_DETAILINFO
(
  SLNO          NUMBER,
  CARDNO        VARCHAR2(15 BYTE),
  FINYEAR       NUMBER,
  FINMONTH      VARCHAR2(15 BYTE),
  LEAVE_TYPE    VARCHAR2(35 BYTE),
  START_DATE    DATE,
  END_DATE      DATE,
  LEAVEDAY      NUMBER,
  SALDAY        NUMBER,
  LEAVE_STATUS  VARCHAR2(80 BYTE),
  PROCESSDATE   DATE,
  UPDATEED      DATE,
  UPDATEBY      VARCHAR2(50 BYTE),
  COMPANY       VARCHAR2(200 BYTE),
  REASON        VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_BONUS_AMOUNT
(
  FINYEAR    NUMBER,
  FINMONTH   VARCHAR2(15 BYTE),
  CARDNO     VARCHAR2(15 BYTE),
  JOBPERIOD  NUMBER,
  GROSSSAL   NUMBER(15,2),
  BASICSAL   NUMBER(15,2),
  BPERCENT   VARCHAR2(50 BYTE),
  BAMOUNT    NUMBER(15,2),
  COMPANY    VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_TOTALDAY_TEMP
(
  SECRETENO        VARCHAR2(15 BYTE),
  CARDNO           VARCHAR2(15 BYTE),
  FINYEAR          NUMBER,
  FINMONTH         VARCHAR2(12 BYTE),
  TOTALDAY         NUMBER,
  TOTALHOLIDAY     NUMBER,
  COMPENSIVE       NUMBER,
  CASUAL           NUMBER,
  EARNED           NUMBER,
  MEDICAL          NUMBER,
  TOTALLEAVE       NUMBER,
  TOTALWORKINGDAY  NUMBER,
  TOTALATTDENCE    NUMBER,
  TOTALPRESENT     NUMBER,
  TOTALABSENT      NUMBER,
  ATTBONUS         VARCHAR2(5 BYTE),
  OTHR             VARCHAR2(15 BYTE),
  OTMIN            NUMBER,
  OTMINPART        NUMBER,
  EXTRADAY         NUMBER,
  EXTRA_OT         NUMBER,
  LATEDAY          NUMBER,
  COMPANY          VARCHAR2(250 BYTE),
  NT_DAY           NUMBER,
  HALF_OT          NUMBER,
  HOLIDAY_DUTY     NUMBER,
  FESDAY_DUTY      NUMBER,
  EXDAY_DUTY       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_TOTALDAY
(
  SECRETENO        VARCHAR2(15 BYTE),
  CARDNO           VARCHAR2(15 BYTE),
  FINYEAR          NUMBER,
  FINMONTH         VARCHAR2(12 BYTE),
  TOTALDAY         NUMBER,
  TOTALHOLIDAY     NUMBER,
  COMPENSIVE       NUMBER,
  CASUAL           NUMBER,
  EARNED           NUMBER,
  MEDICAL          NUMBER,
  TOTALLEAVE       NUMBER,
  TOTALWORKINGDAY  NUMBER,
  TOTALATTDENCE    NUMBER,
  TOTALPRESENT     NUMBER,
  TOTALABSENT      NUMBER,
  ATTBONUS         VARCHAR2(5 BYTE),
  OTHR             VARCHAR2(15 BYTE),
  OTMIN            NUMBER,
  OTMINPART        NUMBER,
  EXTRADAY         NUMBER,
  EXTRA_OT         NUMBER,
  LATEDAY          NUMBER,
  COMPANY          VARCHAR2(250 BYTE),
  NT_DAY           NUMBER,
  HALF_OT          NUMBER,
  HOLIDAY_DUTY     NUMBER,
  FESDAY_DUTY      NUMBER,
  EXDAY_DUTY       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_ARREARAMOUNT_INFO
(
  SLID         NUMBER,
  COMPANY      VARCHAR2(255 BYTE),
  CARDNO       VARCHAR2(15 BYTE),
  PAYYEAR      NUMBER,
  PAYMONTH     VARCHAR2(15 BYTE),
  PAYAMT       NUMBER,
  REMARKS      VARCHAR2(255 BYTE),
  PROCESSDATE  DATE,
  PROCESSBY    VARCHAR2(40 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_SALARY_TEMP
(
  FINYEAR          NUMBER,
  FINMONTH         VARCHAR2(15 BYTE),
  CARDNO           VARCHAR2(15 BYTE),
  EMPNAME          VARCHAR2(150 BYTE),
  GROSSSAL         NUMBER(15,2),
  BASICSAL         NUMBER(15,2),
  HOUSERENT        NUMBER(15,2),
  MEDICAL          NUMBER(15,2),
  TRANSPORT        NUMBER(15,2),
  ATTBONUS         NUMBER,
  OTHERALLOW       NUMBER,
  PFUND            NUMBER(15,2),
  OTRATE           NUMBER(15,2),
  OTAMOUNT         NUMBER(15,2),
  TOTALSALARY      NUMBER(15,2),
  ABSENT_DEDUC     NUMBER(15,2),
  ADVANCE_DEDUC    NUMBER(15,2),
  ARREAR_AMT       NUMBER(15,2),
  OTHER_DEDUC      NUMBER,
  HALF_DUTY_DEDUC  NUMBER,
  LUNCH_BILL       NUMBER,
  TAXDEDUCTION     NUMBER(15,2),
  NETPAYABLE       NUMBER(15,2),
  STAMP            NUMBER(15,2),
  NETPAYMENT       NUMBER(15,2),
  USELESS          NUMBER(15,2),
  COMPANY          VARCHAR2(200 BYTE),
  PROCESSDATE      DATE,
  EXTRA_OTAMT      NUMBER,
  NT_BILL          NUMBER,
  EXTRA_BILL       NUMBER,
  FDALLOW          NUMBER                       DEFAULT 0,
  SAL_GRD          VARCHAR2(5 BYTE),
  DESIGNATION      VARCHAR2(115 BYTE),
  HOLIDAY_BILL     NUMBER,
  FESDAY_BILL      NUMBER,
  EXDAY_BILL       NUMBER,
  SAL_STATUS       VARCHAR2(2 BYTE),
  PAY_STATUS       VARCHAR2(2 BYTE),
  FS_BONUS         NUMBER,
  HRENT_DED        NUMBER,
  SALPENALTY_DED   NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_MONTH_SALARY
(
  FINYEAR          NUMBER,
  FINMONTH         VARCHAR2(15 BYTE),
  CARDNO           VARCHAR2(15 BYTE),
  EMPNAME          VARCHAR2(150 BYTE),
  GROSSSAL         NUMBER(15,2),
  BASICSAL         NUMBER(15,2),
  HOUSERENT        NUMBER(15,2),
  MEDICAL          NUMBER(15,2),
  TRANSPORT        NUMBER(15,2),
  ATTBONUS         NUMBER,
  OTHERALLOW       NUMBER,
  PFUND            NUMBER(15,2),
  OTRATE           NUMBER(15,2),
  OTAMOUNT         NUMBER(15,2),
  TOTALSALARY      NUMBER(15,2),
  ABSENT_DEDUC     NUMBER(15,2),
  ADVANCE_DEDUC    NUMBER(15,2),
  ARREAR_AMT       NUMBER(15,2),
  OTHER_DEDUC      NUMBER,
  HALF_DUTY_DEDUC  NUMBER,
  LUNCH_BILL       NUMBER,
  TAXDEDUCTION     NUMBER(15,2),
  NETPAYABLE       NUMBER(15,2),
  STAMP            NUMBER(15,2),
  NETPAYMENT       NUMBER(15,2),
  USELESS          NUMBER(15,2),
  COMPANY          VARCHAR2(200 BYTE),
  PROCESSDATE      DATE,
  EXTRA_OTAMT      NUMBER,
  NT_BILL          NUMBER,
  EXTRA_BILL       NUMBER,
  FDALLOW          NUMBER                       DEFAULT 0,
  SAL_GRD          VARCHAR2(5 BYTE),
  DESIGNATION      VARCHAR2(115 BYTE),
  HOLIDAY_BILL     NUMBER,
  FESDAY_BILL      NUMBER,
  EXDAY_BILL       NUMBER,
  SAL_STATUS       VARCHAR2(2 BYTE),
  PAY_STATUS       VARCHAR2(2 BYTE),
  FS_BONUS         NUMBER,
  HRENT_DED        NUMBER,
  SALPENALTY_DED   NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_OUT
(
  MACNO      VARCHAR2(20 BYTE),
  SECRETENO  VARCHAR2(15 BYTE),
  PDATE      DATE,
  PTIME      VARCHAR2(15 BYTE),
  STATUS     VARCHAR2(15 BYTE),
  PEXIT      VARCHAR2(15 BYTE),
  COMPANY    NUMBER,
  CARDNO     VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_MASTER
(
  CARDNO       VARCHAR2(15 BYTE),
  SECRETENO    VARCHAR2(15 BYTE),
  PDATE        DATE,
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  OTSTART      VARCHAR2(15 BYTE),
  DURATION     VARCHAR2(6 BYTE),
  LATEHR       VARCHAR2(8 BYTE),
  EARLYHR      VARCHAR2(8 BYTE),
  OTMIN        NUMBER,
  OTPART       NUMBER,
  LATESTATUS   VARCHAR2(15 BYTE),
  EARLYSTATUS  VARCHAR2(30 BYTE),
  COMPANY      NUMBER,
  YES_NOT      NUMBER,
  ISLN         INTEGER                          DEFAULT 0,
  SECTIONNM    VARCHAR2(150 BYTE),
  SHIFT        VARCHAR2(3 BYTE),
  LINENO       VARCHAR2(5 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_MASTER_TEMP
(
  CARDNO       VARCHAR2(15 BYTE),
  SECRETENO    VARCHAR2(15 BYTE),
  PDATE        DATE,
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  OTSTART      VARCHAR2(15 BYTE),
  DURATION     VARCHAR2(6 BYTE),
  LATEHR       VARCHAR2(8 BYTE),
  EARLYHR      VARCHAR2(15 BYTE),
  OTMIN        NUMBER,
  OTPART       NUMBER,
  LATESTATUS   VARCHAR2(15 BYTE),
  EARLYSTATUS  VARCHAR2(30 BYTE),
  COMPANY      NUMBER,
  YES_NOT      NUMBER,
  ISLN         NUMBER                           DEFAULT 0,
  SECTIONNM    VARCHAR2(100 BYTE),
  SHIFT        VARCHAR2(3 BYTE),
  LINENO       VARCHAR2(5 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_INFO_RESIGNATION
(
  EMPID             NUMBER,
  DEPARTMENTNM      VARCHAR2(100 BYTE),
  SECTIONNM         VARCHAR2(100 BYTE),
  LINENO            VARCHAR2(50 BYTE),
  CARDNO            VARCHAR2(15 BYTE),
  SECRETENO         VARCHAR2(15 BYTE),
  EMPNAME           VARCHAR2(100 BYTE),
  FATHER_NAME       VARCHAR2(100 BYTE),
  MOTHER_NAME       VARCHAR2(100 BYTE),
  PRESENT_ADDRESS   VARCHAR2(255 BYTE),
  JOINING_DATE      DATE,
  DESIGNATION       VARCHAR2(150 BYTE),
  SALARY_GRADE      VARCHAR2(20 BYTE),
  GROSSSALARY       NUMBER,
  RESIGNATION_DATE  DATE,
  BIRTH_DATE        DATE,
  TSALARY           NUMBER,
  GENDER            VARCHAR2(30 BYTE),
  BLOODGROUP        VARCHAR2(25 BYTE),
  SHIFT             VARCHAR2(20 BYTE),
  WORKERTYPE        VARCHAR2(50 BYTE),
  HOUSBANDNAME      VARCHAR2(150 BYTE),
  PERMANENTADDRESS  VARCHAR2(255 BYTE),
  COMPANY           VARCHAR2(250 BYTE),
  ACTIVE            NUMBER,
  PF                VARCHAR2(10 BYTE),
  INRAMT            NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_INFO_SIGN
(
  EMPID         NUMBER,
  DEPARTMENTNM  VARCHAR2(100 BYTE),
  SECTIONNM     VARCHAR2(100 BYTE),
  CARDNO        VARCHAR2(15 BYTE),
  SECRETENO     VARCHAR2(15 BYTE),
  COMPANY       VARCHAR2(250 BYTE),
  EMPSIGN       BLOB
)
TABLESPACE USRPICTURE
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (EMPSIGN) STORE AS 
      ( TABLESPACE  USERS 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          16K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_INFO_PICTURE
(
  EMPID         NUMBER,
  DEPARTMENTNM  VARCHAR2(100 BYTE),
  SECTIONNM     VARCHAR2(100 BYTE),
  CARDNO        VARCHAR2(15 BYTE),
  SECRETENO     VARCHAR2(15 BYTE),
  COMPANY       VARCHAR2(250 BYTE),
  EMPPICTURE    BLOB
)
TABLESPACE USRPICTURE
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (EMPPICTURE) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_INFO_OTHER
(
  DEPARTMENTNM      VARCHAR2(100 BYTE),
  CARDNO            VARCHAR2(15 BYTE),
  SECRETENO         VARCHAR2(15 BYTE),
  BOOK_SL_NO        VARCHAR2(50 BYTE),
  OPEN_DATE         DATE,
  EDUCATION         VARCHAR2(252 BYTE),
  PURPOSEOFWORK     VARCHAR2(250 BYTE),
  PERHRPRODUCTION   VARCHAR2(250 BYTE),
  PERFORMANCE       VARCHAR2(15 BYTE),
  COMPANY           VARCHAR2(250 BYTE),
  NID               VARCHAR2(100 BYTE),
  SECTIONNM         VARCHAR2(150 BYTE),
  REF1              VARCHAR2(150 BYTE),
  REF2              VARCHAR2(150 BYTE),
  COMPANY_JOB1      VARCHAR2(250 BYTE),
  DESIGNATION_JOB1  VARCHAR2(150 BYTE),
  START_DATE_JOB1   DATE,
  END_DATE_JOB1     DATE,
  COMPANY_JOB2      VARCHAR2(250 BYTE),
  DESIGNATION_JOB2  VARCHAR2(150 BYTE),
  START_DATE_JOB2   DATE,
  END_DATE_JOB2     DATE,
  COMPANY_JOB3      VARCHAR2(250 BYTE),
  DESIGNATION_JOB3  VARCHAR2(150 BYTE),
  START_DATE_JOB3   DATE,
  END_DATE_JOB3     DATE,
  CELL_NO           VARCHAR2(15 BYTE),
  CHILDRENNO        NUMBER                      DEFAULT 0,
  NOMINEE_NAME      VARCHAR2(150 BYTE),
  RELATION          VARCHAR2(50 BYTE),
  NOMINEE_ADDRESS   VARCHAR2(150 BYTE),
  EXPERIENCE_YR     NUMBER                      DEFAULT 0,
  HEIGHT            VARCHAR2(8 BYTE),
  WEIGHT            VARCHAR2(8 BYTE),
  SPECIAL_MARK      VARCHAR2(100 BYTE),
  OWN_CELLNO        VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_EMPLOYMENT
(
  EMPID          NUMBER,
  CARDNO         VARCHAR2(15 BYTE),
  COMPANYNAME    VARCHAR2(250 BYTE),
  START_DATE     DATE,
  END_DATE       DATE,
  DESIGNATION    VARCHAR2(110 BYTE),
  ADDRESS        VARCHAR2(200 BYTE),
  EMPLOYER_TYPE  VARCHAR2(20 BYTE),
  COMPANY        VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_INFO
(
  EMPID               NUMBER,
  DEPARTMENTNM        VARCHAR2(100 BYTE),
  SECTIONNM           VARCHAR2(100 BYTE),
  LINENO              VARCHAR2(50 BYTE),
  CARDNO              VARCHAR2(15 BYTE),
  SECRETENO           VARCHAR2(15 BYTE),
  EMPNAME             VARCHAR2(100 BYTE),
  FATHER_NAME         VARCHAR2(100 BYTE),
  MOTHER_NAME         VARCHAR2(100 BYTE),
  PRESENT_ADDRESS     VARCHAR2(255 BYTE),
  JOINING_DATE        DATE,
  DESIGNATION         VARCHAR2(150 BYTE),
  SALARY_GRADE        VARCHAR2(20 BYTE),
  GROSSSALARY         NUMBER,
  RESIGNATION_DATE    DATE,
  BIRTH_DATE          DATE,
  EMPPICTURE          BLOB,
  TSALARY             NUMBER,
  GENDER              VARCHAR2(30 BYTE),
  BLOODGROUP          VARCHAR2(25 BYTE),
  SHIFT               VARCHAR2(20 BYTE),
  WORKERTYPE          VARCHAR2(50 BYTE),
  HOUSBANDNAME        VARCHAR2(150 BYTE),
  PERMANENTADDRESS    VARCHAR2(255 BYTE),
  COMPANY             VARCHAR2(250 BYTE),
  ACTIVE              NUMBER,
  PF                  VARCHAR2(10 BYTE),
  INRAMT              NUMBER,
  UPDATE_DATE         DATE,
  UPDATE_BY           VARCHAR2(50 BYTE),
  OTORG               VARCHAR2(1 BYTE),
  OTCOM               VARCHAR2(1 BYTE),
  WDAY                VARCHAR2(15 BYTE),
  RELIGION            VARCHAR2(18 BYTE),
  MOBILE              NUMBER,
  OTHER               NUMBER,
  BANKNAME            VARCHAR2(200 BYTE),
  ACNO                VARCHAR2(35 BYTE),
  ATM_CARDNO          VARCHAR2(35 BYTE),
  MOBILE_BANKACNO     VARCHAR2(35 BYTE),
  PAYMENT_TYPE        VARCHAR2(10 BYTE),
  ENMNAME_BANGLA      VARCHAR2(100 BYTE),
  DESIGNATION_BANGLA  VARCHAR2(100 BYTE),
  DEPT_BANGLA         VARCHAR2(100 BYTE),
  SEC_BANGLA          VARCHAR2(100 BYTE),
  MARITAL_STATUS      VARCHAR2(15 BYTE),
  PAY_SAL             VARCHAR2(2 BYTE),
  PAY_OTHER           VARCHAR2(2 BYTE)
)
TABLESPACE USRPICTURE
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (EMPPICTURE) STORE AS 
      ( TABLESPACE  SYSTEM 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        STORAGE    (
                    INITIAL          24K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    FREELISTS        1
                    FREELIST GROUPS  1
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PERSONAL_EDUCATIONAL
(
  EMPID           NUMBER,
  CARDNO          VARCHAR2(15 BYTE),
  HIGHEST_DEGREE  VARCHAR2(220 BYTE),
  LEVEL_DEGREE    VARCHAR2(50 BYTE),
  INSTITUTE_NAME  VARCHAR2(220 BYTE),
  PASSING_YR      NUMBER,
  CLASS_GRADE     VARCHAR2(10 BYTE),
  SUBJECT         VARCHAR2(150 BYTE),
  COMPANY         VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_ROASTER_INFO
(
  RSID          NUMBER,
  SECRETENO     VARCHAR2(15 BYTE),
  CARDNO        VARCHAR2(15 BYTE),
  RDATE         DATE,
  RDAY          VARCHAR2(25 BYTE),
  PRESENTSHIFT  VARCHAR2(5 BYTE),
  CHANGESHIFT   VARCHAR2(5 BYTE),
  TIMESLOT      VARCHAR2(5 BYTE),
  COMPANYID     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_SALARY_HALF_AMOUNT
(
  FINYEAR     NUMBER,
  FINMONTH    VARCHAR2(25 BYTE),
  CARDNO      VARCHAR2(10 BYTE),
  JOINDATE    DATE,
  TOTSALARY   NUMBER,
  OTHERSAL    NUMBER,
  GROSSSAL    NUMBER,
  SALAMOUNT   NUMBER,
  WORKERTYPE  VARCHAR2(50 BYTE),
  PER         NUMBER,
  COMPANY     VARCHAR2(250 BYTE),
  NETPAYMENT  NUMBER,
  RPAYMENT    NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          960K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_JOB_CARD_TEMP
(
  CARDNO       VARCHAR2(15 BYTE),
  EMPNAME      VARCHAR2(200 BYTE),
  DESIGNATION  VARCHAR2(150 BYTE),
  SECTIONNM    VARCHAR2(100 BYTE),
  JOININGDATE  DATE,
  GROSSSAL     NUMBER                           DEFAULT 0,
  MONTHDATE    DATE,
  WEEKSTATUS   VARCHAR2(20 BYTE),
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  OTHR         NUMBER                           DEFAULT 0,
  LATESTATUS   VARCHAR2(10 BYTE),
  OFFDAY       VARCHAR2(15 BYTE),
  PSTATUS      VARCHAR2(5 BYTE),
  DURATION     VARCHAR2(5 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(15 BYTE),
  COMPANY      VARCHAR2(250 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_MASTER_ARCV
(
  CARDNO       VARCHAR2(15 BYTE),
  SECRETENO    VARCHAR2(15 BYTE),
  PDATE        DATE,
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  OTSTART      VARCHAR2(15 BYTE),
  DURATION     VARCHAR2(6 BYTE),
  LATEHR       VARCHAR2(8 BYTE),
  EARLYHR      VARCHAR2(8 BYTE),
  OTMIN        NUMBER,
  OTPART       NUMBER,
  LATESTATUS   VARCHAR2(15 BYTE),
  EARLYSTATUS  VARCHAR2(30 BYTE),
  COMPANY      NUMBER,
  YES_NOT      NUMBER,
  ISLN         NUMBER                           DEFAULT 0,
  SECTIONNM    VARCHAR2(150 BYTE),
  SHIFT        VARCHAR2(3 BYTE),
  LINENO       VARCHAR2(5 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(15 BYTE),
  OTHR         NUMBER                           DEFAULT 0,
  OTHRPART     NUMBER                           DEFAULT 0,
  PSATUS       VARCHAR2(2 BYTE),
  STATUSDAY    VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_MOVEMENT
(
  MACNO      VARCHAR2(20 BYTE),
  CARDNO     VARCHAR2(15 BYTE),
  SECRETENO  VARCHAR2(15 BYTE),
  PDATE      DATE,
  PTIME      VARCHAR2(15 BYTE),
  STATUS     VARCHAR2(15 BYTE),
  COMPANY    NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_MASTER_TEMP_ARCV
(
  CARDNO       VARCHAR2(15 BYTE),
  SECRETENO    VARCHAR2(15 BYTE),
  PDATE        DATE,
  INTIME       VARCHAR2(15 BYTE),
  OUTTIME      VARCHAR2(15 BYTE),
  OTSTART      VARCHAR2(15 BYTE),
  DURATION     VARCHAR2(6 BYTE),
  LATEHR       VARCHAR2(8 BYTE),
  EARLYHR      VARCHAR2(15 BYTE),
  OTMIN        NUMBER,
  OTPART       NUMBER,
  LATESTATUS   VARCHAR2(15 BYTE),
  EARLYSTATUS  VARCHAR2(30 BYTE),
  COMPANY      NUMBER,
  YES_NOT      NUMBER,
  ISLN         NUMBER                           DEFAULT 0,
  SECTIONNM    VARCHAR2(100 BYTE),
  SHIFT        VARCHAR2(3 BYTE),
  LINENO       VARCHAR2(5 BYTE),
  FINYEAR      NUMBER,
  FINMONTH     VARCHAR2(15 BYTE),
  OTHR         NUMBER                           DEFAULT 0,
  OTHRPART     NUMBER                           DEFAULT 0,
  PSATUS       VARCHAR2(2 BYTE),
  STATUSDAY    VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_DATA_MOVEMENT_TEMP
(
  MACNO      VARCHAR2(20 BYTE),
  CARDNO     VARCHAR2(15 BYTE),
  SECRETENO  VARCHAR2(15 BYTE),
  PDATE      DATE,
  PTIME      VARCHAR2(15 BYTE),
  STATUS     VARCHAR2(15 BYTE),
  COMPANY    NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_PROCESS_INFO
(
  PROCESS_NAME  VARCHAR2(200 BYTE),
  DELETE_DATA   VARCHAR2(200 BYTE),
  PROCESS_DATE  DATE,
  PROCESS_BY    VARCHAR2(30 BYTE),
  COMPANY       VARCHAR2(250 BYTE),
  USENESS       VARCHAR2(200 BYTE),
  USENESS1      VARCHAR2(200 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TB_WINDOW_PROCESS
(
  PDATE        DATE,
  PROCESSNAME  VARCHAR2(150 BYTE),
  PROCESSBY    VARCHAR2(45 BYTE),
  REMARKS      VARCHAR2(150 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX QUEST_COM_PRODUCTS_PK ON QUEST_COM_PRODUCTS
(PRODUCT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          448K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX QUEST_COM_PRDUCTS_U2 ON QUEST_COM_PRODUCTS
(PRODUCT_PREFIX)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX QUEST_COM_PRODUCT_U1 ON QUEST_COM_PRODUCTS
(PRODUCT_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX QUEST_COM_PRODUCTS_USED_BY_PK ON QUEST_COM_PRODUCTS_USED_BY
(PRODUCT_ID, USED_BY_PRODUCT_ID)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX QUEST_COM_PRODUCT_PRIVS_PK ON QUEST_COM_PRODUCT_PRIVS
(PRODUCT_ID, PRIVILEGE_ID)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX QUEST_COM_USERS_PK ON QUEST_COM_USERS
(USER_ID, PRODUCT_ID)
NOLOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_ADVANCE_LOAN ON TB_ADVANCEORLOAN_INFO
(COMPANY, LOANYEAR, LOANMONTH, DUDUCYEAR, DEDUCMONTH, 
CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_ARREAR_INFO ON TB_ARREARAMOUNT_INFO
(COMPANY, PAYYEAR, PAYMONTH, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_BONUS_AMT ON TB_BONUS_AMOUNT
(COMPANY, FINYEAR, FINMONTH, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_BONUS_SETUP ON TB_BONUS_SETUP
(BONUS_YEAR, BONUS_MONTH, BONUS_EMP_TYPE, BONUS_MIN_DAYS)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_COMPANY_NAME ON TB_COMPANY_INFO
(COMPANY)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_DATA_MASTER ON TB_DATA_MASTER
(COMPANY, FINYEAR, FINMONTH, PDATE, CARDNO)
LOGGING
TABLESPACE USRPICTURE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_DATA_MASTER_ARCV ON TB_DATA_MASTER_ARCV
(COMPANY, FINYEAR, FINMONTH, PDATE, CARDNO)
LOGGING
TABLESPACE USRPICTURE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_DATA_MASTER_TM ON TB_DATA_MASTER_TEMP
(COMPANY, FINYEAR, FINMONTH, PDATE, CARDNO)
LOGGING
TABLESPACE USRPICTURE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_DATA_MASTER_TM_ARCV ON TB_DATA_MASTER_TEMP_ARCV
(COMPANY, FINYEAR, FINMONTH, PDATE, CARDNO)
LOGGING
TABLESPACE USRPICTURE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_DEPARTMENT ON TB_DEPARTMENT_INFO
(DEPT_NAME)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_DESIGNATION ON TB_DESIGNATION_INFO
(DESIGNATION)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_DUTY_SCHEDULE ON TB_DUTY_SCHEDULE_SETUP
(COMPANY, SECTION_WORKER, SHIFT)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_EMP_DED_BILL ON TB_EMP_DEDUCTION_BILL
(COMPANY, FINYEAR, FINMONTH, STATUS, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_EMP_LUNCH_BILL ON TB_EMP_LAUNCH_BILL
(COMPANY, FINYEAR, FINMONTH, STATUS, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_EMP_PUNISHMENT ON TB_EMP_PUNISHMENT_RECORD
(COMPANY, FINYEAR, FINMONTH, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_JOB_CARD ON TB_JOB_CARD
(COMPANY, FINYEAR, FINMONTH, MONTHDATE, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_JOB_CARD_TM ON TB_JOB_CARD_TEMP
(COMPANY, FINYEAR, FINMONTH, MONTHDATE, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_LEAVE_DETAIL ON TB_LEAVE_DETAILINFO
(COMPANY, FINYEAR, FINMONTH, CARDNO, START_DATE)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_LEAVE_MASTER ON TB_LEAVE_MASTERINFO
(COMPANY, FINYEAR, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_MONTH_EMP_OT ON TB_MONTH_EMP_OT
(COMPANY, FINYEAR, FINMONTH, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_MONTH_GENHOLIDAY ON TB_MONTH_GENERALHOLIDAY
(COMPANY, FINYEAR, FINMONTH, S_DATE)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_MONTH_HOLI_CUTT ON TB_MONTH_GENERAL_DAYADDCUT
(COMPANY, FINYEAR, FINMONTH, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_MONTH_SALARY ON TB_MONTH_SALARY
(COMPANY, FINYEAR, FINMONTH, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_MONTH_SALARY_TM ON TB_MONTH_SALARY_TEMP
(COMPANY, FINYEAR, FINMONTH, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_MONTH_DAY ON TB_MONTH_TOTALDAY
(COMPANY, FINYEAR, FINMONTH, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_MONTH_DAY_TM ON TB_MONTH_TOTALDAY_TEMP
(COMPANY, FINYEAR, FINMONTH, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_PERFORMANCE_MONTH ON TB_PERFORMANCE_MONTHLY
(COMPANY, FINYEAR, EMPNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PERFORMANCE_YRLY ON TB_PERFORMANCE_YEARLY
(COMPANY, FINYEAR, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_PERSONAL_INFO ON TB_PERSONAL_INFO
(COMPANY, CARDNO)
LOGGING
TABLESPACE USRPICTURE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PERSONAL_BANGLA ON TB_PERSONAL_INFO_BANGLA
(ECOMPANY, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PERSONAL_OTHER ON TB_PERSONAL_INFO_OTHER
(COMPANY, CARDNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PERSONAL_PICTURE ON TB_PERSONAL_INFO_PICTURE
(COMPANY, CARDNO)
LOGGING
TABLESPACE USRPICTURE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_PERSONAL_SIGN ON TB_PERSONAL_INFO_SIGN
(COMPANY, CARDNO)
NOLOGGING
TABLESPACE USRPICTURE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_MONTH_PF_AMT ON TB_PF_MONTHLY_AMT
(COMPANY, FINYEAR, FINMONTH, EMPNO)
NOLOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_PROCESS_PRIVILEGES ON TB_PROCESS_PRIVILEGES
(PRO_ID, USER_NAME, USER_MODE)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_PROMOTION_INFO ON TB_PROMOTION_INFO
(COMPANY, PROYEAR, FINMONTH, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_ROASTER_INFO ON TB_ROASTER_INFO
(COMPANYID, RDATE, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IDX_SALARY_HF_AMT ON TB_SALARY_HALF_AMOUNT
(COMPANY, FINYEAR, FINMONTH, CARDNO)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_SECTION_INFO ON TB_SECTION_INFO
(DEPARTTMENTNM, SECTIONNM)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX IDX_WEEKLY_HOLIDAY ON TB_WEEKLY_HOLIDAY
(COMPANY, FINYEAR, FINMONTH)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE QUEST_COM_USERS ADD (
  CONSTRAINT QUEST_COM_USERS_PK
 PRIMARY KEY
 (USER_ID, PRODUCT_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE QUEST_COM_PRODUCT_PRIVS ADD (
  CONSTRAINT QUEST_COM_PRODUCT_PRIVS_PK
 PRIMARY KEY
 (PRODUCT_ID, PRIVILEGE_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE QUEST_COM_PRODUCTS_USED_BY ADD (
  CONSTRAINT QUEST_COM_PRODUCTS_USED_BY_PK
 PRIMARY KEY
 (PRODUCT_ID, USED_BY_PRODUCT_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE QUEST_COM_PRODUCTS ADD (
  CONSTRAINT QUEST_COM_PRODUCTS_PK
 PRIMARY KEY
 (PRODUCT_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          448K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

ALTER TABLE QUEST_COM_PRODUCTS ADD (
  CONSTRAINT QUEST_COM_PRDUCTS_U2
 UNIQUE (PRODUCT_PREFIX)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

ALTER TABLE QUEST_COM_PRODUCTS ADD (
  CONSTRAINT QUEST_COM_PRODUCT_U1
 UNIQUE (PRODUCT_NAME)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE QUEST_COM_USER_PRIVILEGES ADD (
  CONSTRAINT QUEST_COM_USER_PRIVS_FK2 
 FOREIGN KEY (USER_ID, PRODUCT_ID) 
 REFERENCES QUEST_COM_USERS (USER_ID,PRODUCT_ID));

ALTER TABLE QUEST_COM_USER_PRIVILEGES ADD (
  CONSTRAINT QUEST_COM_USER_PRIV_FK1 
 FOREIGN KEY (PRODUCT_ID, PRIVILEGE_ID) 
 REFERENCES QUEST_COM_PRODUCT_PRIVS (PRODUCT_ID,PRIVILEGE_ID)
    ON DELETE CASCADE);


ALTER TABLE QUEST_COM_USERS ADD (
  CONSTRAINT QUEST_COM_USERS_FK1 
 FOREIGN KEY (PRODUCT_ID) 
 REFERENCES QUEST_COM_PRODUCTS (PRODUCT_ID)
    ON DELETE CASCADE);


ALTER TABLE QUEST_COM_PRODUCT_PRIVS ADD (
  CONSTRAINT QUEST_COM_PRODUCT_PRIVS_FK1 
 FOREIGN KEY (PRODUCT_ID) 
 REFERENCES QUEST_COM_PRODUCTS (PRODUCT_ID)
    ON DELETE CASCADE);


ALTER TABLE QUEST_COM_PRODUCTS_USED_BY ADD (
  CONSTRAINT QUEST_COM_PRODUCTS_USED_BY_FK1 
 FOREIGN KEY (PRODUCT_ID) 
 REFERENCES QUEST_COM_PRODUCTS (PRODUCT_ID)
    ON DELETE CASCADE);

ALTER TABLE QUEST_COM_PRODUCTS_USED_BY ADD (
  CONSTRAINT QUEST_COM_PRODUCTS_USED_BY_FK2 
 FOREIGN KEY (USED_BY_PRODUCT_ID) 
 REFERENCES QUEST_COM_PRODUCTS (PRODUCT_ID)
    ON DELETE CASCADE);


GRANT DELETE, INSERT, SELECT, UPDATE ON  QUEST_COM_PRODUCTS TO PUBLIC;

GRANT DELETE, INSERT, SELECT, UPDATE ON  QUEST_COM_PRODUCTS_USED_BY TO PUBLIC;

GRANT DELETE, INSERT, SELECT, UPDATE ON  QUEST_COM_PRODUCT_PRIVS TO PUBLIC;

GRANT DELETE, INSERT, SELECT, UPDATE ON  QUEST_COM_USERS TO PUBLIC;

GRANT DELETE, INSERT, SELECT, UPDATE ON  QUEST_COM_USER_PRIVILEGES TO PUBLIC;


