select * from tb_personal_info where cardno='10001152'

SELECT * FROM TB_DATA_MASTER WHERE FINYEAR=2019 and (
	   CARDNO,(SUBSTR(TO_CHAR(pdate, 'DL' ),1,INSTR(TO_CHAR(pdate,'DL'),',')-1))
	   ) in (select cardno,WDAY from tb_personal_info where cardno='10001152')
	   and finmonth='January';


DECLARE
DAY01 DATE:=TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY02 DATE:=TO_DATE('01/02/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY03 DATE:=TO_DATE('01/03/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY04 DATE:=TO_DATE('01/04/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY05 DATE:=TO_DATE('01/05/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY06 DATE:=TO_DATE('01/06/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY07 DATE:=TO_DATE('01/07/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY08 DATE:=TO_DATE('01/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY09 DATE:=TO_DATE('01/09/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY10 DATE:=TO_DATE('01/10/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY11 DATE:=TO_DATE('01/11/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY12 DATE:=TO_DATE('01/12/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
DAY13 DATE:=TO_DATE('01/13/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');

CARDNOS VARCHAR(20);

BEGIN
DBMS_OUTPUT.PUT_LINE(DAY01);
DBMS_OUTPUT.PUT_LINE();
END;


SELECT * FROM TB_DATA_MASTER WHERE PDATE=TO_DATE('01/04/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
AND CARDNO IN (SELECT CARDNO FROM TB_PERSONAL_INFO WHERE active=0 and sectionnm='Admin')


select TO_CHAR(to_date('01.11.2019','dd.mm.yyyy')+level-1,'DL'),to_date('01.11.2019','dd.mm.yyyy')+level-1
 from dual 
 connect by level <= TO_CHAR(LAST_DAY(to_date('01.11.2019','dd.mm.yyyy')),'DD')
 

	
SELECT
TO_CHAR(TO_DATE('01/02/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),'DL') dt,
  SUBSTR(TO_CHAR(TO_DATE('01/03/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS') , 'DL' ),1,INSTR(TO_CHAR(TO_DATE('01/03/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),'DL'),',')-1),
  INSTR(TO_CHAR(TO_DATE('01/02/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),'DL'),',')
FROM
  dual;
  
  

select * from tb_data_master where 
(cardno,pdate) in (('10001152',TO_DATE('01/02/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS')));




SELECT * FROM TB_ADVANCEORLOAN_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY

SELECT * FROM TB_ARREARAMOUNT_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY

SELECT * FROM TB_COMPANY_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY

SELECT * FROM TB_DEPARTMENT_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_DUTY_SCHEDULE_SETUP
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_EMP_CARD_CHANGE
WHERE PROCESSBY='NDL'
AND PROCESSDATE between TO_DATE(:TODAY_S||'12:00:10', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')


SELECT * FROM TB_EMP_CARD_DELETE
WHERE PROCESSBY='NDL'
AND PROCESSDATE between TO_DATE(:TODAY_S||'12:00:10', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')


SELECT * FROM TB_EMP_CARD_REJOIN
WHERE PROCESSBY='NDL'
AND PROCESSDATE between TO_DATE(:TODAY_S||'12:00:10', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')

SELECT * FROM TB_EMP_DEDUCTION_BILL
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_EMP_HALF_DUTY
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_EMP_HOLIDAY_ALLOW
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_EMP_LATE_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE between TO_DATE(:TODAY_S||'12:00:00', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')


SELECT * FROM TB_EMP_LAUNCH_BILL
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_EMP_PUNISHMENT_RECORD
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_EMP_TAX_AMOUNT
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_GRATUITY_DETAILS_AMT
WHERE PROCESSBY='NDL'
AND PROCESSDATE between TO_DATE(:TODAY_S||'12:00:00', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')



SELECT * FROM TB_LEAVE_DETAILINFO
WHERE UPDATEBY='NDL'
AND UPDATEED=:TODAY


SELECT * FROM TB_LEAVE_MASTERINFO
WHERE UPDATEBY='NDL'
AND UPDATEED between TO_DATE(:TODAY_S||'12:00:00', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')


SELECT * FROM TB_LEAVE_SUMMARY
WHERE PROCESSBY='NDL'
AND PROCESSDATE between TO_DATE(:TODAY_S||'00:00:00', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')


SELECT * FROM TB_MANUAL_ATTENDENCE
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_MONTHLY_ATTEND_SUMMARY
WHERE PROCESSBY='NDL'
AND PROCESSDATE between TO_DATE(:TODAY_S||'00:00:00', 'MM/DD/YYYY HH24:MI:SS') and TO_DATE(:TODAY_S||'23:59:00', 'MM/DD/YYYY HH24:MI:SS')


SELECT * FROM TB_MONTH_GENERAL_DAYADDCUT
WHERE UPDATEBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_PERSONAL_INFO
WHERE PROCESS_BY='NDL'
AND PROCESS_DATE=:TODAY


SELECT * FROM TB_PROMOTION_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_RESIGNATION_INFO
WHERE PROCESS_BY='NDL'
AND PROCESS_DATE=:TODAY


SELECT * FROM TB_SECTION_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY


SELECT * FROM TB_TRANSFER_INFO
WHERE PROCESSBY='NDL'
AND PROCESSDATE=:TODAY




-----------------------------



select count(distinct pr_info.cardno),count(distinct data_master.cardno),pr_info.lineno,
pr_info.sectionnm,pr_info.departmentnm
from tb_personal_info pr_info,tb_data_master data_master
where pr_info.cardno=data_master.cardno
and data_master.pdate=TO_DATE('01/01/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS')
group by pr_info.departmentnm,pr_info.sectionnm,pr_info.lineno


-----------------------------



select * from TB_EMP_ABSENT_LETTER
where finyear=2019
and finmonth='November'
and cardno='000006'

----------------------------