CREATE OR REPLACE TRIGGER AUTO_INCREMENT_SL
BEFORE INSERT
   ON TB_REQ_BILL
   FOR EACH ROW
DECLARE
   TEMPVAR NUMBER:=0;

BEGIN
   SELECT MAX(SL) INTO TEMPVAR FROM TB_REQ_BILL;
   :NEW.SL:=(TEMPVAR+1);
END;
/