UPDATE TB_DATA_MASTER_TEMP
SET OTMIN=:OT_MIN,OTMIN_V=:OT_MIN
WHERE COMPANY=(
	  SELECT COMID FROM TB_COMPANY_INFO
	  WHERE COMPANY=:COMPANY_NAME
)
AND FINYEAR=:LAST_YEAR
AND FINMONTH=:LAST_MONTH
AND TO_NUMBER(
		SUBSTR(DURATION,0,INSTR(DURATION,':')-1),'9G999D99'
		) > :CONDITIONAL_DURATION


/*
SELECT * FROM TB_DATA_MASTER_TEMP
WHERE COMPANY=2
AND FINYEAR=2019
AND FINMONTH='February'
AND TO_NUMBER(SUBSTR(DURATION,0,INSTR(DURATION,':')-1),'9G999D99') > 10


SELECT * FROM TB_DATA_MASTER_TEMP
WHERE COMPANY=2
AND FINYEAR=2019
AND FINMONTH='February'
AND TO_NUMBER(SUBSTR(DURATION,0,INSTR(DURATION,':')-1),'9G999D99') > 9
AND OTMIN=0
*/
