
-- ** UPDATE SINGLE DATE OUT TIME AND OT 
	 
DECLARE
	   FINYEARS NUMBER := 2019;
	   FINMONTHS VARCHAR2(15 BYTE):= 'March';
	   CARD VARCHAR2(15 BYTE):= '018917';
	   PDATES   DATE := TO_DATE('03/10/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS');
	   
	   FINTIME VARCHAR2(15 BYTE);
	   FINHOUR VARCHAR2(6 BYTE);
	   FINOTMIN NUMBER;
BEGIN   
	SELECT (TO_CHAR(SUBSTR(OUTTIME,1,2)-2/*DUCT NUMBER*/)||':'||
		   TO_CHAR((SUBSTR(OUTTIME,4,2)))||':'||
		   TO_CHAR((SUBSTR(OUTTIME,7,2)))||' PM'),
		   
		   TO_CHAR(SUBSTR(DURATION,1,INSTR(DURATION,':')-1)-2/*DUCT NUMBER*/)||':'||
		   SUBSTR(DURATION,INSTR(DURATION,':')+1,2),
		   
		   (((TO_NUMBER(SUBSTR(DURATION,1,INSTR(DURATION,':')-1))-2/*DUCT NUMBER*/)-9)*60)
		   
	INTO FINTIME,FINHOUR,FINOTMIN
		   
	FROM  NEW_TABLE
	WHERE FINYEAR=FINYEARS
	AND	  FINMONTH=FINMONTHS
	AND	  CARDNO=CARD
	AND   PDATE=PDATES;
		   
	UPDATE TB_DATA_MASTER
	SET 
		OUTTIME=FINTIME,
		OUTTIME_V=FINTIME,
		DURATION=FINHOUR,
		DURATION_V=FINHOUR,
		OTMIN=FINOTMIN,
		OTMIN_V=FINOTMIN
		
	WHERE  FINYEAR=FINYEARS
	AND	   FINMONTH=FINMONTHS
	AND	   CARDNO=CARD
	AND    PDATE = PDATES;
	
END;